/*______________
|       ______  |   B U I L T     O N     U I Z E     F R A M E W O R K
|     /      /  |   ---------------------------------------------------
|    /    O /   |   This JavaScript application is developed using the object
|   /    / /    |   oriented UIZE JavaScript framework as its foundation.
|  /    / /  /| |
| /____/ /__/_| |    ONLINE : http://www.uize.com
|          /___ |   LICENSE : Available under MIT License or GNU General Public License
|_______________|             http://www.uize.com/license.html
*/

/*______________
|       ______  |   U I Z E    J A V A S C R I P T    F R A M E W O R K
|     /      /  |   ---------------------------------------------------
|    /    O /   |    MODULE : UizeDotCom.WidgetToGoPage.library Library Module
|   /    / /    |
|  /    / /  /| |    ONLINE : http://www.uize.com
| /____/ /__/_| | COPYRIGHT : (c)2009-2010 UIZE
|          /___ |   LICENSE : Available under MIT License or GNU General Public License
|_______________|             http://www.uize.com/license.html
*/

/*?
	Introduction
		The =UizeDotCom.WidgetToGoPage.library= module is a library module that bundles together various JavaScript modules common to all pages of the UIZE JavaScript Framework's Web site that use the =UizeDotCom.WidgetToGoPage= page widget class.

		*DEVELOPERS:* `Chris van Rensburg`
*/



Uize.module({name:'UizeDotCom'});


Uize.module({name:'Uize.Node',builder:function(){var _a=function(){},_b,_c='string',_d='function',_e=true,_f=false,_g=null,_h=navigator,_i=_h.userAgent.toLowerCase(),_j=_h.appName=='Microsoft Internet Explorer',_k=_i.indexOf('applewebkit')> -1,_l=_i.indexOf('gecko')> -1,_m=_i.indexOf('opera')> -1,_n=_l||_m,_o='hidden',_p=Uize.copyInto;var _q=_a._q=function(_r){_s.clientX=_r.clientX;_s.clientY=_r.clientY;};function _t(_u){var _v=document.getElementById(_u);return(!_j||(_v&&_v.id==_u))?_v:_g;}function _w(){var _x=document[_k?'body':'documentElement'];return{scrollLeft:_x.scrollLeft,scrollTop:_x.scrollTop};}function _y(_z){var _A=(_z=_z+'').slice(_z.indexOf('(')+1,_z.indexOf(')'));return Function.apply({},(_A?_A.split(','):[]).concat(_z.slice(_z.indexOf('{')+1,_z.lastIndexOf('}'))));}function _B(_C){if(_C.charCodeAt(0)==111&&_C.charCodeAt(1)==110)_C=_C.slice(2);return(_C.charCodeAt(_C.length-1)==41&&_a.VirtualEvent?_a.VirtualEvent.resolve(_C):_C);}function _D(_E,_F){for(
var _G= -1,_v={},_H=Math.min(_E.length,_F.length);++_G<_H;)_v[_E[_G]]=_F[_G];return _v;}var _I=_a._I={},_J={},_K=0,_L={string:1,number:1,boolean:1},_s={clientX:0,clientY:0};var _M='table-',_N=_M+'row',_O=_M+'cell',_P=_p({SPAN:'inline',THEAD:_M+'header-group',TFOOT:_M+'footer-group',LI:'list-item'},_j&&typeof DOMImplementation=='undefined'?_g:{TABLE:'table',TR:_N,TH:_O,TD:_O,TBODY:_N+'-group',COLGROUP:_M+'column-group',COL:_M+'column',CAPTION:_M+'caption'});_a.display=function(_Q,_R){_R=_R===_b|| !!_R;_S(_Q,function(_T){_T.style.display=_R?(_P[_T.tagName]||'block'):'none';});};var _S=_a.doForAll=function(_Q,_z,_U,_V){if(typeof _Q==_c)_Q=_W(_Q,_U,_V);if(_Q!=_b){if(_X(_Q)){_z(_Q);}else{var _Y=typeof _Q;if((_Y=='object'||_Y==_d)&&typeof _Q.length=='number'){for(var _Z= -1,_0=_Q.length;++_Z<_0;)_S(_Q[_Z],_z,_U,_V);}else if(_Y=='object'){for(var _1 in _Q)_S(_Q[_1],_z,_U,_V);}}}};var _2=_a.doRectanglesOverlap=function(_3,_4,_5,_6,_7,_8,_9,_ba){return(_5-1+ +_3>=_7&&_9-1+ +_7>=_3&&_6-1+ +_4>=_8&&_ba-1+ +_8>=_4);};
var _W=_a.getById=function(_T,_U,_V){if(typeof _T!=_c)return _T;var _v=_V?_V[_T]:_b;if(_v===_b){var _bb=_bc(_U,_T);(_v=_t(_bb))||(((_v=document.getElementsByName(_bb)).length<2)&&(_v=_v[0]||_g));if(_V)_V[_T]=_v;}return _v;};_a.find=function(_bd){if(typeof _bd!='object'|| !_bd||typeof _bd.length=='number'||_X(_bd))return _bd;var _be=document,_bf=[],_bg=_p({},_bd),_bh='root'in _bg?_W(_bg.root):_be;delete _bg.root;if(_bh){var _bi=_bg.tagName;if('id'in _bg&&_L[typeof _bg.id]){var _T=_t(_bg.id);_T&&_bf.push(_T);delete _bg.id;}else if('name'in _bg&&_L[typeof _bg.name]){_bf=_be.getElementsByName(_bg.name);delete _bg.name;}else{var _bj=_L[typeof _bi];_bj&&delete _bg.tagName;_bf=_bh.getElementsByTagName(_bi&&_bj?_bi:'*');_bh=_g;}if(_bh==_be)_bh=_g;if(!_bi||_bi=='*')delete _bg.tagName;}var _bk=_bf.length;for(var _bl in _bg)break;if(!_bk||(_bl==_b&& !_bh))return _bf;var _bm=[],_bn;for(var _bo= -1;++_bo<_bk;){var _T=_bf[_bo];if(_bn=_bh?_bp(_T,_bh):_e){for(var _bq in _bg){var _br=_T[_bq],_bs=_bg[_bq],_bt=typeof _bs;if(!(
_L[_bt]?_br==_bs:(_bs instanceof RegExp?_bs.test(_br||''):(_bt==_d?_bs.call(_T,_br):_e)))){_bn=_f;break;}}}_bn&&_bm.push(_T);}return _bm;};var _bu=_a.getCoords=function(_T){var _bv=0,_bw=0,_bx=0,_by=0,_bz=_e,_bA=_w(),_bB=_bC(window);function _bD(){_bv+=_bA.scrollLeft;_bw+=_bA.scrollTop;}if(_T==window){_bD();_bx=_bB.width;_by=_bB.height;}else if(_X(_T=_W(_T))){_bx=_T.offsetWidth;_by=_T.offsetHeight;if(!(_bx&&_by)&&_T.tagName=='DIV'){for(var _bE=_T.childNodes,_bF=_bE.length;--_bF>=0;){if(_bE[_bF].nodeName.charAt(0)!='#'){var _bG=_bu(_bE[_bF]);if(_bG.width||_bG.height){_bx=Math.max(_bx,_bG.right-_bv+1);_by=Math.max(_by,_bG.bottom-_bw+1);}}}}function _bH(_T){return _bI(_T,'display')=='none'||_bI(_T,'visibility')==_o;}if(_T.tagName=='A'&&_T.childNodes.length==1&&_T.childNodes[0].tagName=='IMG')_T=_T.childNodes[0];var _bJ=_bz= !_bH(_T),_bK=_T,_bL=_T;while(_bL.parentNode&&typeof _bL.parentNode!='unknown'){var _bM=_bL.offsetLeft||0,_bN=_bL.offsetTop||0,_bO=_bL.offsetWidth,_bP=_bL.offsetHeight;if(_bz&&_bH(_bL))_bz=_f;
if(_bL==_bK){_bv+=_bM+(parseInt(_bI(_bL,'borderLeftWidth'))||0);_bw+=_bN+(parseInt(_bI(_bL,'borderTopWidth'))||0);_bK=_bL.offsetParent;_bI(_bL,'position')=='fixed'&&_bD();}if(_bL!=_T&&_bL!=document.body&&_bL!=document.documentElement&&(_bL.scrollWidth>_bO||_bL.scrollHeight>_bP)){_bv-=_bL.scrollLeft;_bw-=_bL.scrollTop;if(_j){_bv+=_bL.clientLeft;_bw+=_bL.clientTop;}if(_bz)_bz=_2(_bv,_bw,_bx,_by,_bM,_bN,_bO,_bP);}_bL=_bL.parentNode;}if(_bz)_bz=_2(_bv,_bw,_bx,_by,_bA.scrollLeft,_bA.scrollTop,_bB.width,_bB.height);}return{x:_bv,y:_bw,width:_bx,height:_by,area:_bx*_by,left:_bv,top:_bw,right:_bv+_bx-1,bottom:_bw+_by-1,seen:_bz};};var _bC=_a.getDimensions=function(_T){if(_T==window){var _x=document.documentElement;return{width:_x.clientWidth||window.innerWidth||_x.offsetWidth,height:_x.clientHeight||window.innerHeight||_x.offsetHeight};}else if(_T=_W(_T)){return{width:_T.offsetWidth||parseInt(_bI(_T,'width'))||0,height:_T.offsetHeight||parseInt(_bI(_T,'height'))||0};}else{return{width:0,height:0};}};
_a.getEffectiveBgColor=function(_T){var _bQ='';_T=_W(_T);while((!_bQ||_bQ=='transparent'||_bQ=='none')&&_T){_bQ=_bI(_T,'backgroundColor');_T=_T.parentNode;}return _bQ;};var _bR=_a.getOpacityProperties=function(_bS){return _j?{filter:'alpha(opacity='+Math.round(_bS*100)+')'}:{opacity:_bS+''};};_a.getOpacityStr=function(_bS){return _bT(_bR(_bS));};var _bU={borderColor:['border','Color'],borderWidth:['border','Width'],padding:1,margin:1},_bI=_a.getStyleAttribute=_a.getStyle=function(_T,_bV){var _bW='';if(typeof _bV==_c){if(_T){var _bX=_j&&_bV=='opacity',_bY=document.defaultView,_bZ=_bY&&_bY.getComputedStyle(_T,'');if(_bX)_bV='filter';if(_bZ){if(!(_bW=_bZ[_bV])){var _b0=_bU[_bV];if(_b0){var _b1=_b0[0]||_bV,_b2=_b0[1]||'',_b3=_bZ[_b1+'Top'+_b2],_b4=_bZ[_b1+'Right'+_b2],_b5=_bZ[_b1+'Bottom'+_b2],_b6=_bZ[_b1+'Left'+_b2];_bW=_b3==_b4&&_b4==_b5&&_b5==_b6?_b6:_b3+' '+_b4+' '+_b5+' '+_b6;}}}else{var _b7=_T.currentStyle;_bW=_b7?_b7.getAttribute(_bV):_T.style[_bV];}if(_bX){
var _b8=_bW.match(/alpha\s*\(\s*opacity\s*=([^\)]*)\)/i);_bW=_b8?_b8[1]/100:1;}}}else{_bW={};if(_T)for(_bV in _bV)_bW[_bV]=_bI(_T,_bV);}return _bW;};var _b9=_a.getText=function(_T){var _ca='';if(_T=_W(_T)){function _cb(_T){if(typeof _T.innerText==_c){_ca=_T.innerText.replace(/\r|\n|\r\n/g,'');}else if(typeof _T.textContent==_c){_ca=_T.textContent;}else{if(_T.nodeType==3)_ca=_T.data;if(_T.childNodes){for(var _bF= -1,_bE=_T.childNodes,_cc=_bE.length;++_bF<_cc;)_ca+=_b9(_bE[_bF]);}}}_cb(_T);}return _ca;};_a.getValue=function(_T){var _bW;if(_T=_W(_T)){if(_X(_T)){var _cd=_T.tagName;if(_cd=='TEXTAREA'){_bW=_T.value;}else if(_cd=='INPUT'){_bW=_T.type=='checkbox'?_T.checked:_T.value;}else if(_cd=='SELECT'){if(_T.multiple){_bW=[];for(var _ce= -1,_cf=_T.options,_cg=_cf.length,_ch;++_ce<_cg;)(_ch=_cf[_ce]).selected&&_bW.push(_ch.value);}else{_bW=_T.value;}}else if(_cd=='IMG'){_bW=_T.src;}else{_bW=_T.innerHTML.replace(/<br\/?>/gi,'\n').replace(/&nbsp;/g,' ');}}else{
_bW=(Uize.findRecord(_T,{tagName:'INPUT',type:'radio',checked:_e})||{}).value;}}return _bW;};_a.injectHtml=function(_Q,_ci,_cj){var _ck,_cl,_cm,_cn,_co,_cp;((_ck=_cj=='inner replace')||(_cl=_cj=='outer replace')||(_cm=_cj=='inner top')||(_cn=_cj=='outer top')||(_co=_cj=='outer bottom')||(_cp=_e));_ci+='';_S(_Q,function(_T){var _cq=_T.childNodes;function _cr(_cs){return _cs&&/<script/i.test(_cs);}function _ct(){return _cr(_ci);}if((_ck||(!_cq.length&&(_cm||_cp)))&& !_ct()){_T.innerHTML=_ci;}else if(_cl&&_j&& !_ct()){_T.outerHTML=_ci;}else{if(_ck)_T.innerHTML='';var _cu=document.createElement('DIV');_cu.innerHTML=_ci;var _cv=_cm?_cq[0]:_co?_T.nextSibling:_T,_cw=_cu.childNodes,_cx=_T.parentNode;function _cy(_T){if(_T.tagName=='SCRIPT'){var _cz=document.createElement('script');if(_T.id)_cz.id=_T.id;if(_T.type)_cz.type=_T.type;_cz.text=_T.text;if(_T.src)_cz.src=_T.src;_T.parentNode.replaceChild(_cz,_T);}else if(_cr(_T.innerHTML)){for(var _bF= -1,_cq=_T.childNodes,_cA=_cq.length;++_bF<_cA;)_cy(_cq[_bF]);}}
while(_cw.length){var _cB=_cw[0];if(_cp||_ck){_T.appendChild(_cB);}else if(_cm){_cv?_T.insertBefore(_cB,_cv):_T.appendChild(_cB);}else if(_cn||_cl){_cx.insertBefore(_cB,_cv);}else if(_co){_cv?_cx.insertBefore(_cB,_cv):_cx.appendChild(_cB);}_cy(_cB);}_cl&&_cx.removeChild(_T);}});};var _X=_a.isNode=function(_T){return!!(_T&&typeof _T=='object'&&(_T.getAttribute||_T.documentElement||(_T.self&&_T.self==_T)));};var _bp=_a.isOnNodeTree=function(_T,_cC){_T=_W(_T);_cC=_W(_cC);while(_T){if(_T==_cC)return _e;_T=_T.parentNode;}return _f;};var _bc=_a.joinIdPrefixAndNodeId=function(_U,_u){return(_U||'')+(_U&&_u?'-':'')+_u;};_a.remove=function(_Q){_S(_Q,function(_T){_T.parentNode.removeChild(_T)});};_a.setClipRect=function(_Q,_b3,_b4,_b5,_b6){var _cD='rect('+_b3+'px, '+_b4+'px, '+_b5+'px, '+_b6+'px)';_S(_Q,function(_T){_T.style.clip=_cD});};var _cE=['left','top','width','height'];_a.setCoords=function(_Q,_cF){_cG(_Q,typeof _cF.length=='number'?_D(_cE,_cF):_cF);};_a.centerInWindow=function(_Q){var _cH=_bu(window);_S(_Q,
function(_T){var _cI=_bC(_T);_a.setCoords(_T,{left:_cH.x+((_cH.width-_cI.width)>>1),top:_cH.y+((_cH.height-_cI.height)>>1)});});};_a.getEventAbsPos=function(_r){var _bA=_w();return{left:(_r||_s).clientX+_bA.scrollLeft,top:(_r||_s).clientY+_bA.scrollTop};};var _cJ=_a.setAbsPos=function(_Q,_cK,_cL){_cL=typeof _cL=='number'?{x:_cL,y:_cL}:(_cL||{x:0,y:0});var _x=document[_k?'body':'documentElement'],_cM=_bC(window);_S(_Q,function(_T){function _cN(_cO,_cP,_cQ,_cR){var _cS=_cK[_cO],_cT=_cL[_cR],_cU=_cS-_x[_cP],_cV=_cT+_cI[_cQ];return(_cS+(_cU+_cV>_cM[_cQ]?Math.max(-_cV,-_cU):_cT));}var _cI=_bC(_T);_cG(_T,{left:_cN('left','scrollLeft','width','x'),top:_cN('top','scrollTop','height','y'),right:'auto',bottom:'auto'});});};_a.setAbsPosAdjacentTo=function(_Q,_cW,_cX){_cW=_W(_cW);var _cY=_bu(_cW),_cZ=_cY.width/2,_c0=_cY.height/2,_c1=_cX=='x'? -1:1;if(!_cZ&& !_c0)_cY=_a.getEventAbsPos();_S(_Q,function(_T){_cJ(_T,{left:_cY.left+_cZ,top:_cY.top+_c0},{x:-_cZ*_c1,y:_c0*_c1});});};_a.setInnerHtml=function(_Q,_cs){_cs+='';
_S(_Q,function(_T){_T.innerHTML=_cs});};var _c2={};_a.setOpacity=function(_Q,_bS){_c2.opacity=_bS;_cG(_Q,_c2);};_a.setProperties=function(_Q,_bd){_S(_Q,function(_T){_p(_T,_bd)});};var _cG=_a.setStyle=function(_Q,_bd){_S(_Q,function(_T){var _c3=_T.style,_c4;if(_j&&'opacity'in _bd)_c3.filter=(_c4=Math.round(_bd.opacity*100))<100?'alpha(opacity='+_c4+')':'';for(var _bV in _bd)_c3[_bV]=(typeof(_c4=_bd[_bV])=='object'&&_c4?(_c4=_c4.valueOf()):_c4)!=_b?(typeof _c4=='number'&&_bV!='opacity'&&_bV!='zIndex'?Math.round(_c4)+'px':_c4+''):'';});};_a.setValue=function(_Q,_bW){_bW+='';_S(_Q,function(_T){var _cd=_T.tagName,_c5=_T.readOnly;if(_c5)_T.readOnly=_f;if(_cd=='TEXTAREA'){_T.value=_bW;}else if(_cd=='INPUT'){var _c6=_T.type;if(_c6=='text'||_c6==_o||_c6=='password'){_T.value=_bW;}else if(_c6=='checkbox'){_T.checked=_bW=='true';}else if(_c6=='radio'){_T.checked=_T.value==_bW;}}else if(_cd=='SELECT'){if(!_bW){_T.selectedIndex= -1;}else{var _cf=_T.options;if(_T.multiple&&(_bW=='*'||_bW.indexOf(',')> -1)){var _c7;
if(_bW!='*'){_c7={};for(var _F=_bW.split(','),_G=_F.length;--_G>=0;)_c7[_F[_G]]=1;}for(var _ce=_cf.length,_ch;--_ce>=0;)(_ch=_cf[_ce]).selected= !_c7||_c7[_ch.value];}else{_T.selectedIndex=Uize.findRecordNo(_cf,{value:_bW},_T.selectedIndex);}}}else if(_cd=='IMG'){if(_bW)_T.src=_bW;}else{_cd=='PRE'&&_j?(_T.innerText=_bW):(_T.innerHTML=_bW.replace(/</g,'&lt;').replace(/\n/g,'<br/>'));}if(_c5)_T.readOnly=_c5;});};_a.show=function(_Q,_c8){_cG(_Q,{visibility:_c8||_c8===_b?'inherit':_o});};_a.showClickable=function(_Q,_c9){_cG(_Q,{cursor:_c9||_c9===_b?(_j?'hand':'pointer'):'default'});};_a.showInLayoutFlow=function(_Q,_c8){_c8=_c8!==_f;_cG(_Q,{position:_c8?'static':'absolute',visibility:_c8?'inherit':_o});};var _bT=_a.stylePropertiesAsStr=function(_bd){var _da=[];for(var _bV in _bd)_da.push(_bV,':',_bd[_bV],'; ');return _da.join('');};var _db=_a.unwire=function(_Q,_dc,_dd,_de){if(typeof _dc=='object'&&_dc&& !_dc.virtualDomEvent){for(var _C in _dc)_db(_Q,_C,_dc[_C],_dd);}else{_a.unwireEventsByOwnerId(_de,
_Q!==_b||_dc!=_b||_dd!=_b?{node:_Q,eventName:_dc,handler:_dd}:_b);}};_a.unwireEventsByOwnerId=function(_df,_dg){var _dh=_J[_df=_df||''];if(_dh){function _di(_dj){if(_dj!==_g){var _dk=_dg&&_dg.eventName,_dl=_dg&&_dg.handler,_dm=_dj||_dk||_dl;if(_dk&&_dk.charCodeAt)_dk=_B(_dk);for(var _dn=_dh.length;--_dn>=0;){var _do=_dh[_dn],_dp=_I[_do],_T=_dp._T,_C=_dp._C;if(!_dm||((!_dj||_dj==(_dp._dq||_T))&&(!_dk||_dk==_C)&&(!_dl||_dl==_dp._dr))){_dm&&_dh.splice(_dn,1);if(_dp._ds){_a.unwireEventsByOwnerId(_dp._ds)}else{try{_T==window?_dt.unwire(_C,_dp._du):_j?_T.detachEvent('on'+_C,_dp._du):_T.removeEventListener(_C,_dp._du,_f);}catch(_dv){}}delete _I[_do];}}(_dm&&_dh.length)||delete _J[_df];}}_dg&&_dg.node!==_b?_S(_dg.node,_di):_di();}};var _dw=_y(function(_do){return(function(_r){var _dp=window.Uize&&Uize.Node._I[_do];return _dp&&_dp._dr.call(_dp._T,_r.windowEvent);});}),_dx=_y(function(_do){return(function(_r){var _dp=window.Uize&&Uize.Node._I[_do];return _dp&&_dp._dr.call(_dp._T,_r||window.event);});}),_dy={click:_dx,
mouseover:_y(function(_do){return(function(_r){var _dp=window.Uize&&Uize.Node._I[_do],_dz=(_r||(_r=window.event)).fromElement||_r.relatedTarget;if(_dp){if(_dz){try{if(!_dz.Uize_Widget_Drag_shield&& !Uize.Node.isOnNodeTree(_dz,_dp._T))_dz=null;}catch(_dv){_dz=null;}}if(!_dz){Uize.Node._q(_r);return _dp._dr.call(_dp._T,_r);}}});}),mouseout:_y(function(_do){return(function(_r){var _dp=window.Uize&&Uize.Node._I[_do],_dA=(_r||(_r=window.event)).toElement||_r.relatedTarget;if(_dp){if(_dA){try{if(!_dA.Uize_Widget_Drag_shield&& !Uize.Node.isOnNodeTree(_dA,_dp._T))_dA=null;}catch(_dv){_dA=null;}}if(!_dA)return _dp._dr.call(_dp._T,_r);}});}),mousedown:_dx,mouseup:_dx};_a.wireEvent=_a.wireEvents=_a.wire=function(_Q,_C,_dr,_df){if(!_C)return;if(_df==_b)_df='';var _dB;if(_C.charCodeAt)_C=_B(_C);if(typeof _C=='object'&& !(_dB= !!_C.virtualDomEvent)){_df=arguments[2]||'';for(var _r in _C)_a.wire(_Q,_r,_C[_r],_df);return;}_S(_Q,function(_T){var _cd=_T.tagName;(_J[_df]||(_J[_df]=[])).push(_K);var _du=(_dB?_a.returnFalse
:_T==window?_dw:_dy[_C]||_dx)(_K);var _dp=_I[_K++]={_T:_T,_C:_C,_dr:_dr,_du:_du};if(_n&&_cd=='BODY'&&_C=='scroll'){_dp._dq=_T;_T=_dp._T=document;}if(_du){var _dC='on'+_C;_T==window?_dt.wire(_C,_du):_j?_T.attachEvent(_dC,_du):_T.addEventListener(_C,_du,_f);if(_cd=='A'&&(_C=='mousedown'||_C=='click')&& !_T[_dC])_T[_dC]=_a.returnFalse;}else if(_dB){_C.wire(_T,_dr,_dp._ds=Uize.getGuid());}});};_a.returnFalse=new Function('return false');_a.returnTrue=new Function('return true');_a.isIe=_j;_a.isSafari=_k;_a.isMozilla=_l;_a.wire(document.documentElement,'mousemove',_q);var _dt=new Uize,_dD=setTimeout(function(){_dt.fire('load')},15000);function _dE(_dF){var _dG='on'+_dF,_dH=window[_dG]||_a.returnFalse;window[_dG]=function(_r){_dF=='load'&&clearTimeout(_dD);_dH.call(window,_r||(_r=event));_dt.fire({name:_dF,windowEvent:_r});};}for(var _dF in{focus:1,blur:1,load:1,beforeunload:1,unload:1,resize:1,scroll:1})_dE(_dF);;return _a;}});


Uize.module({name:'Uize.Widget',required:'Uize.Node',builder:function(b_a){var b_b=null,b_c=true,b_d=false,b_e='string',b_f='function',b_g='concatenated',b_h,b_i=Uize.Node,b_j=b_i.doForAll,b_k=b_i.isNode,b_l=b_i.getById;var b_m=b_a.subclass(function(){this.children=this.b_n={};}),b_o=b_m.prototype;b_o.b_p=function(){if(window['$'+this.b_q]&&(!this.parent||this.b_q!=this.parent.b_q)){var b_r='$'+this.b_q;this.set(window[b_r]);window[b_r]=b_h;}};b_o.b_s=function(b_t,b_u,b_v,b_w){return((b_w==b_g|| !b_w)&&b_t!=b_h?(b_t+(b_v!==''?'_':'')+b_v):(b_w=='same as parent'?b_t:b_u));};var b_x={b_y:b_d,b_z:b_c};b_o.b_A=function(){(this.b_B=='inherit'?(this.parent||b_x).b_y:this.b_B)!=this.b_y&&this.set({b_y:!this.b_y});};b_o.b_C=function(){(this.b_D=='inherit'?(this.parent||b_x).b_z:this.b_D)!=this.b_z&&this.set({b_z:!this.b_z});};b_o.b_E=function(b_F,b_G,b_H){var b_I='show'+b_m.capFirstChar(b_F);this.getProvider(b_I)?this.callInherited(b_I)(b_G):setTimeout(function(){var b_J=b_H();
(b_G.callback||(b_J?b_G.yesHandler:b_G.noHandler)||function(){})(b_J)},0);};b_o.confirm=function(b_G){this.b_E('confirm',b_G,function(){return confirm(b_G.message)});};b_o.showInform=b_o.showConfirm=b_h;b_o.inform=function(b_G){this.b_E('inform',b_G,function(){alert(b_G.message);return b_c});};b_o.localize=function(b_K,b_L,b_M){var b_N,b_O=this;while(!(b_N=b_O.b_P?b_O.b_P[b_K]:b_h)&&(b_O=b_O.parent));return(typeof b_N==b_f?b_N.call(this,b_L):b_m.substituteInto(b_N,b_L,b_M||'{KEY}'));};b_o.buildHtml=function(b_Q){var b_R=this,b_S=b_R.b_S;if(b_S!=b_h){var b_T=b_R.b_U||b_R.getNode('shell')||b_R.getNode();if(b_S===b_c){b_S=b_R.b_S=Uize.Template&&b_T?{process:Uize.Template.compile((b_i.find({root:b_T,tagName:'SCRIPT',type:'text/jst'})[0]||b_T).innerHTML,{openerToken:'[%',closerToken:'%]'})}:b_h;if(!b_S)return;}b_R.b_q||b_R.set({b_q:b_R.instanceId});var b_V=b_m.copyInto({pathToResources:b_R.Class.pathToResources,blankGif:b_m.getBlankImageUrl()},b_Q||b_R.get()),b_W=typeof b_S;b_i.injectHtml(b_T||document.body,
b_W!=b_e&&typeof b_S.process==b_f?b_S.process.call(b_R,b_V):b_m.substituteInto(b_W==b_f?b_R.b_S(b_V):b_S,b_V),b_R.b_X||(b_T?'inner replace':'inner bottom'));b_R.b_Y=b_b;b_R.set({b_Z:b_c});}};b_o.wired=function(){return this.isWired};function b_0(b_1,b_2){b_o[b_1+'Node'+b_2]=new Function('arguments.length'+'?(arguments[0]=this.getNode(arguments[0]))'+':(arguments[arguments.length++]=this.getNode());'+'return Uize.Node.'+b_1+b_2+'.apply(0,arguments)');}b_o.getNode=function(b_3){if(b_3==b_b){if(b_3===b_b)return b_b;b_3='';}var b_R=this;if(b_R.b_4&&typeof b_3==b_e){var b_5=b_R.b_4[b_3];if(b_5!==b_h)b_3=b_5;}if(typeof b_3==b_e){return b_l(b_3,b_R.b_q,b_R.b_Y||(b_R.b_Y={}));}else if(b_k(b_3)){return b_3;}else{var b_6=b_b;b_j(b_3,function(b_7){(b_6||(b_6=[])).push(b_7)},b_R.b_q,b_R.b_Y||(b_R.b_Y={}));return b_6;}};b_0('get','Style');b_0('get','Value');b_o.flushNodeCache=function(b_8){if(this.b_Y)b_8==b_h?(this.b_Y=b_b):delete this.b_Y[b_8];};b_o.globalizeNode=function(b_9){var b_R=this,b_ba=document.body;b_j(
b_R.getNode(b_9),function(b_7){if(b_7.parentNode!=b_ba){(b_R.b_bb||(b_R.b_bb=[])).push(b_7);b_i.setStyle(b_7,{position:'absolute',left:-10000,top:-10000});b_ba.appendChild(b_7);}});};b_0('display','');b_0('inject','Html');b_o.removeNode=function(b_9){b_i.remove(this.getNode(b_9));this.flushNodeCache(b_9);};b_0('set','Properties');b_0('set','Opacity');b_0('set','Style');b_0('set','ClipRect');b_0('set','InnerHtml');b_0('set','Value');b_0('show','');b_o.wireNodeEvent=b_o.wireNodeEvents=b_o.wireNode=function(b_9,b_bc,b_bd){arguments.length==3?b_i.wire(this.getNode(b_9),b_bc,b_bd,this.instanceId):b_i.wire(this.getNode(b_9),b_bc,this.instanceId);};b_o.unwireNodeEvent=b_o.unwireNode=function(b_9,b_bc,b_bd){if(b_9!==b_h)b_9=this.getNode(b_9);arguments.length==2&&typeof b_bc=='object'&&b_bc&& !b_bc.virtualDomEvent?b_i.unwire(b_9,b_bc,this.instanceId):b_i.unwire(b_9,b_bc,b_bd,this.instanceId);};b_o.unwireNodeEventsByMatch=function(b_9,b_be){this.unwireNode(b_9,(b_be||(b_be={})).eventName,b_be.handler);};
b_o.addChild=function(b_v,b_bf,b_bg){if(!b_bg)b_bg={};var b_R=this,b_q=b_R.b_q,b_bh=b_m.isInstance(b_bf)?b_bf:b_b,b_u='idPrefix'in b_bg?b_bg.idPrefix:b_bg.node,b_bi=b_bg.idPrefixConstruction;b_bg.parent=b_R;if(b_v==b_h)b_v=b_bg.name;if(b_bh){if(b_v==b_h)b_v=b_bh.b_bj;if(b_u==b_h)b_u=b_bh.b_q;if(!b_bi)b_bi=b_bh.b_w;}if(!b_bi)b_bi=b_u==b_h?b_g:'explicit';b_bg.idPrefixConstruction=b_bi;b_bg.idPrefix=b_R.b_s(b_q,b_u,b_v,b_bi);b_bg.name=b_v;b_bh&&b_bh.set(b_bg);return b_R.b_n[b_v]=b_bh||new b_bf(b_bg);};b_o.removeChild=function(b_bk){var b_n=this.b_n,b_v=typeof b_bk==b_e||b_m.isNumber(b_bk)?b_bk:b_bk.b_bj,b_bh=b_n[b_v];if(b_bh){b_bh.unwireUi();delete b_bh.parent;delete b_n[b_v];}};b_o.getProvider=function(b_bl){var b_bm=this,b_bn;while(((b_bn=b_bm.get(b_bl))==='inherit'||b_bn===b_h)&&(b_bm=b_bm.parent));return b_bm;};b_o.getInherited=function(b_bl){var b_bo=this.getProvider(b_bl);return b_bo?b_bo.get(b_bl):b_h;};b_o.setInherited=function(b_bg){var b_bo;for(var b_bp in b_bg){if(b_bo=this.getProvider(b_bp))
b_bo.set(b_bp,b_bg[b_bp]);}};b_o.callInherited=function(b_bl){var b_R=this;return(function(){var b_bo=b_R.getProvider(b_bl),b_6;if(b_bo){var b_bq=b_bo.get(b_bl);if(typeof b_bq==b_f)b_6=b_bq.apply(b_bo,arguments);}return b_6;});};b_o.kill=function(){b_m.callOn(this.b_n,'kill');b_a.prototype.kill.call(this);};b_o.insertOrWireUi=function(){this.b_Z?this.wireUi():this.insertUi();};b_o.insertUi=function(){this.buildHtml();this.wireUi();};b_o.removeUi=function(){this.unwireUi();this.removeNode();b_i.remove(this.b_bb);this.b_bb=b_h;b_m.callOn(this.b_n,'removeUi');this.set({b_Z:b_d});};b_o.updateUi=function(){};b_o.wireUi=function(){if(!this.isWired){this.b_p();this.set({wired:b_c});var b_n=this.b_n;for(var b_v in b_n)b_n[b_v].insertOrWireUi();this.updateUi();}};b_o.unwireUi=function(){if(this.isWired){this.b_Y=b_b;this.unwireNode();b_m.callOn(this.b_n,'unwireUi');this.set({wired:b_d});}};b_m.getBlankImageUrl=function(){return Uize.pathToResources+'Uize/blank.gif';};b_m.spawn=function(b_bg,b_br){var b_R=this,b_bs=[],
b_bm,b_bt=b_br&&b_br.b_q?b_br.b_q+'_':'',b_bu=b_bt.length;b_j(Uize.Node.find(b_bg.idPrefix),function(b_7){b_bg.idPrefix=b_7;b_br?(b_bm=b_br.addChild(b_7.id.slice(0,b_bu)==b_bt?b_7.id.slice(b_bu):'generatedChildName'+b_m.getGuid(),b_R,b_bg)):(b_bm=new b_R(b_bg)).insertOrWireUi();b_bs.push(b_bm);});return b_bs;};b_m.registerProperties({b_Z:{name:'built',value:b_c},b_B:{name:'busy',onChange:b_o.b_A,value:'inherit'},b_y:{name:'busyInherited',onChange:function(){b_m.callOn(this.b_n,b_o.b_A)},value:b_d},b_U:'container',b_D:{name:'enabled',onChange:b_o.b_C,value:'inherit'},b_z:{name:'enabledInherited',onChange:function(){b_m.callOn(this.b_n,b_o.b_C)},value:b_c},b_S:'html',b_q:{name:'idPrefix|node',conformer:function(b_q){return b_k(b_q)?(b_q.id||(b_q.id=Uize.getGuid())):b_q;},onChange:function(){var b_R=this,b_q=b_R.b_q;b_R.b_Y=b_b;if(b_q!=b_h){b_R.b_p();var b_n=b_R.b_n,b_bh;for(var b_v in b_n)(b_bh=b_n[b_v]).set({b_q:b_R.b_s(b_q,b_bh.b_q,b_v,b_bh.b_w)});if(b_R.isWired){b_R.set({wired:b_d});b_R.wireUi();}}}},
b_w:'idPrefixConstruction',b_X:'insertionMode',b_P:'localized',b_bj:'name',b_4:'nodeMap',isWired:{name:'wired',value:b_d}});function b_bv(b_bw,b_bx){b_i.wire(window,b_bw,function(){b_m.fire(b_bx)});}b_bv('load','Document Loaded');b_bv('unload','Document Unload');b_bv('resize','Window Resized');b_bv('scroll','Window Scrolled');return b_m;}});


Uize.module({name:'Uize.Widget.Page',builder:function(c_a){var c_b=true,c_c=false,c_d;var c_e=c_a.subclass(),c_f=c_e.prototype;c_f.c_g=function(c_h,c_i,c_j){var c_k=this;c_k.useDialog({component:c_k.c_l.component,widgetClassName:c_k.c_l.widgetClassName||'Uize.Widget.Dialog.Confirm',widgetProperties:{name:'confirmDialog',title:c_j.title||'',message:(c_j.message+'').replace(/\n/g,'<br/>'),mode:c_h,state:c_j.state||c_i,okText:c_j.okText||null,cancelText:c_j.cancelText||null},submitHandler:function(c_m){var c_n=c_j.callback||(c_m?c_j.yesHandler:c_j.noHandler);c_n&&c_n(c_m);}});};c_f.useDialog=function(c_j){var c_k=this,c_o=c_j.widgetProperties,c_p=c_o.parent||c_k,c_q=c_o.name,c_r=c_p.children[c_q],c_s=c_j.component,c_t;if(c_s){var c_u=c_o.idPrefix||(c_p.get('idPrefix')+'_'+c_q);c_t={name:c_s.name,rootNodeId:c_u,params:c_e.copyInto({idPrefix:c_u},c_s.params)};}function c_v(c_w){var c_x=c_k.get('productType');c_r.fire({name:'Track Event',extra:c_w+(c_x?(' ('+c_x+')'):''),bubble:c_b});}function c_y(c_z){setTimeout(
function(){function c_A(c_B,c_C){var c_n=c_j[c_B];c_n&&c_n.apply(0,c_C);}function c_D(c_E){var c_C=[c_E];c_A(c_E.name.toLowerCase()+'Handler',c_C);c_A('dismissHandler',c_C);}c_r.unwire(c_r.eventHandlersForUseDialog||{});c_r.eventHandlersForUseDialog={'Submission Complete':function(c_E){c_A('submitHandler',[c_E.result,c_E])},Close:c_D,Cancel:c_D};c_r.wire(c_r.eventHandlersForUseDialog);c_r.set(c_o);c_r.set({shown:c_b});c_v(c_z);},0);}if(c_r&&(c_r.componentProfile==c_t||Uize.Data.identical(c_r.componentProfile,c_t))){c_y('subsequent');}else{var c_F=c_t&& !!c_r;if(c_F){c_r.removeUi();c_p.removeChild(c_q);}function c_G(){var c_H=c_j.widgetClassName;Uize.module({required:c_H,builder:function(){c_r=c_p.addChild(c_q,eval(c_H),c_o);c_r.componentProfile=c_t;c_r.wire(c_j.widgetEventHandlers);c_r.insertOrWireUi();c_y(c_F?'refetched':'initial');}});}c_t?c_k.loadComponentIntoNode({rootNodeId:c_t.rootNodeId,componentParams:c_e.copyInto({cp:c_t.name},c_t.params),injectMode:'inner bottom',alwaysReplace:c_c,callback:c_G})
:c_G();}};c_f.wireUi=function(){var c_k=this;if(!c_k.isWired){var c_I=c_k.get('idPrefix');function c_J(c_K,c_L){var c_M,c_N;for(var c_O in c_L)(typeof(c_M=c_K[c_O])=='object'&&typeof(c_N=c_L[c_O])=='object'&&c_M&&c_N)?c_J(c_M,c_N):(c_K[c_O]=c_L[c_O]);}var c_P={},c_Q=c_c,c_R='$'+c_I+'_',c_S=c_R.length,c_T;for(var c_O in window){if(c_O.charAt(0)=='$'&&c_O.substr(0,c_S)==c_R&&typeof(c_T=window[c_O])=='object'&&c_T&&c_T.widgetClass){c_Q=c_b;for(var c_U= -1,c_V=c_P,c_W=c_O.substr(c_S).split('_'),c_X=c_W.length;++c_U<c_X;){var c_Y=c_W[c_U],c_Z=c_V[c_Y];if(c_U<c_X-1){if(!c_Z)c_Z=c_V[c_Y]={};c_V=c_Z.children||(c_Z.children={});}else{c_Z?c_J(c_Z,c_T):(c_V[c_Y]=c_T);window[c_O]=c_d;}}}}if(c_Q){function c_0(c_1,c_2){function c_3(c_4,c_5,c_6){var c_7=c_6.children,c_8=c_1(c_4,c_5,c_6);c_7&&c_9(c_8,c_7);c_2&&c_2(c_8);}function c_9(c_4,c_ba){for(var c_5 in c_ba)c_3(c_4,c_5,c_ba[c_5]);}c_9(c_k,c_P);}var c_bb={},c_bc=[];c_0(function(c_4,c_5,c_6){var c_bd=c_6.widgetClass;if(c_bd&& !c_bb[c_bd]){c_bb[c_bd]=1;c_bc.push(c_bd);}});
Uize.module({required:c_bc,builder:function(){c_0(function(c_4,c_5,c_6){var c_8=c_4.children[c_5],c_bd=c_6.widgetClass||Uize.Widget;delete c_6.widgetClass;delete c_6.children;c_8?c_8.set(c_6):(c_8=c_5.charCodeAt(0)==36&&c_5.charCodeAt(1)==36?eval(c_bd).spawn(c_6,c_4):c_4.addChild(c_5,eval(c_bd),c_6));return c_8;},c_k.isWired?function(c_8){c_e.callOn(c_8,'insertOrWireUi')}:0);}});}c_a.prototype.wireUi.call(c_k);}};var c_be={yes:1,on:1,1:1,'true':1};c_e.launchPopup=c_f.launchPopup=function(c_j){if(!c_j)c_j={};if(c_j.width==c_d)c_j.width=850;if(c_j.height==c_d)c_j.height=600;var c_bf=window.screen;if(c_j.left==c_d)c_j.left=Math.max((c_bf.width-c_j.width-10)>>1,0);if(c_j.top==c_d)c_j.top=Math.max((c_bf.height-c_j.height-40)>>1,0);function c_bg(c_bh){return c_bh+'='+c_j[c_bh];}function c_bi(c_bh,c_bj){return(c_bh+'='+(c_be[c_j[c_bh]==c_d?c_bj:c_j[c_bh]+'']?'yes':'no'));}var c_bk=window.open(c_j.url||'',c_j.name||'popupWindow',[c_bg('width'),c_bg('height'),c_bg('top'),c_bg('left'),c_bi('toolbar',0),
c_bi('location',0),c_bi('directories',0),c_bi('status',0),c_bi('menubar',0),c_bi('scrollbars',1),c_bi('resizable',1)].join(','));c_bk&&c_bk.focus();return c_bk;};c_e.registerProperties({c_l:{name:'confirmDialog',value:{}}});c_e.set({idPrefix:'page'});c_f.showConfirm=function(c_j){this.c_g('confirm','confirm',c_j);};c_f.showInform=function(c_j){this.c_g('alert','info',c_j);};return c_e;}});


Uize.module({name:'UizeDotCom.Templates'});


Uize.module({name:'UizeDotCom.Templates.WidgetToGoTitle',builder:function(){var _a=function(){};_a.process=function(input){var output=[];output.push('\r\n<div class="widgetHeader">\r\n	<div id="page-title" class="widgetTitle">\r\n		<div class="logo"></div>\r\n		<div class="textShadow">',input.title,'</div>\r\n		<div class="textHighlight">',input.title,'</div>\r\n		<div class="textMain">',input.title,'</div>\r\n	</div>\r\n</div>\r\n\r\n');return output.join('');};_a.input={title:'string'};return _a;}});


Uize.module({name:'UizeDotCom.WidgetToGoPage',superclass:'Uize.Widget.Page',required:'UizeDotCom.Templates.WidgetToGoTitle',builder:function(d_a){var d_b=d_a.subclass(),d_c=d_b.prototype;d_c.wireUi=function(){var d_d=this;if(!d_d.isWired){Uize.Node.injectHtml(document.body,UizeDotCom.Templates.WidgetToGoTitle.process({title:document.title}));Uize.module({required:[d_d.d_e,d_d.d_f],builder:function(){d_d.addChild('widget',eval(d_d.d_e),{built:false,html:eval(d_d.d_f)}).insertOrWireUi();}});d_d.wireNode('title','click',
function(){page.launchPopup({url:'http://www.uize.com',width:1010,height:690});});d_a.prototype.wireUi.call(d_d);}};d_b.registerProperties({d_e:'widgetClass',d_f:'widgetHtml',d_g:'title'});return d_b;}});

Uize.module ({name:'UizeDotCom.WidgetToGoPage.library'});

