/*
	UIZE JAVASCRIPT FRAMEWORK 2010-01-24

	http://www.uize.com/reference/Uize.Widget.Collection.Dynamic.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Widget.Collection.Dynamic',required:['Uize.Node','Uize.Widget.Drag','Uize.Tooltip'],builder:function(d_a){var d_b=true,d_c=false,d_d=null,d_e=Uize.Node,d_f=Uize.Tooltip;var d_g=d_a.subclass(d_d,function(){var d_h=this;var d_i,d_j,d_k,d_l,d_m,d_n,d_o,d_p,d_q,d_r,d_s,d_t,d_u,d_v,d_w,d_x,d_y,d_z=d_h.addChild('drag',Uize.Widget.Drag,{node:d_d});function d_A(d_B){var d_C=d_B?.2:1,d_D=d_h.getNode('tooltipDragging');for(var d_E= -1;++d_E<d_l;)d_k[d_E].setNodeOpacity('',d_C);d_B&&d_e.setInnerHtml(d_D,d_h.localize('draggingToReorder'+(d_l>1?'Plural':'Singular'),{totalItems:d_l}));d_f.showTooltip(d_D,d_B);}d_z.wire({'Drag Start':function(){d_j=d_h.d_F=='reverse'?1:0;d_i.set({over:d_c});var d_G=d_i.get('selected');d_G||d_h.selectAll(d_c);d_k=d_G?d_h.getSelected():[d_i];d_l=d_k.length;d_m=[];d_h.forAll(function(d_H){d_m.push(d_e.getCoords(d_H.getNode()));});var d_I=d_m.length,d_J=d_I-1,d_K=d_m[d_j?d_J:0],d_L=d_m[d_j?d_J-1:1];d_u=d_J&&d_L.top>d_K.bottom?1:0;d_x=d_u?'top':'left';
d_y=d_u?'height':'width';d_p=d_q=d_r=d_s=d_t=d_d;d_v=d_h.getNode('insertionMarker');d_w=d_e.getDimensions(d_v);for(var d_M= -1,d_N=d_J?d_L[d_x]-(d_K[d_x]+d_K[d_y]-1):0,d_O=d_N/2;++d_M<d_I;){var d_P=d_m[d_M];d_P[d_x]-=d_O;d_P[d_y]+=d_N;}d_A(d_b);},'Drag Update':function(){var d_Q=document.documentElement,d_R=d_z.eventPos,d_S=d_e.getEventAbsPos();d_S=[d_S.left,d_S.top];function d_T(d_U){return(d_U&&d_e.doRectanglesOverlap(d_U.left,d_U.top,d_U.width,d_U.height,d_S[0],d_S[1],1,1));}if(!d_T(d_o)){d_n=d_o=d_d;d_h.forAll(function(d_H,d_M){var d_P=d_m[d_M];if(d_T(d_P)){d_n=d_H;d_o=d_P;}return!d_n;});}if(!d_T(d_r)){d_p=d_r=d_d;if(d_n&& !d_g.isIn(d_k,d_n)){var d_V=d_o[d_y],d_W=d_V/2,d_X=d_o[d_x],d_Y=d_X+d_W;d_p=d_n;d_q=d_S[d_u]<d_Y?0:1;d_r=d_g.clone(d_o);d_r[d_x]=d_q?d_Y:d_X;d_r[d_y]=d_W;}}if(d_p!=d_s||d_q!=d_t){d_h.displayNode(d_v,!!d_p);if(d_p){var d_Z=d_g.clone(d_r);d_Z[d_x]+=(d_q?d_r[d_y]:0)-d_w[d_y]/2;delete d_Z[d_y];d_e.setCoords(d_v,d_Z);}d_s=d_p;d_t=d_q;}d_z.set({cursor:d_p||d_n?'move':'not-allowed'});},
'Drag Done':function(d_0){if(d_z.get('dragStarted')){d_A(d_c);d_h.displayNode('insertionMarker',d_c);function d_1(){if(d_p&& !d_z.get('dragCancelled')){var d_2=d_h.itemWidgets;if(d_q^d_j){var d_3=d_2.length,d_4=d_g.indexIn(d_2,d_p)+1;d_p=d_d;while(d_4<d_3){var d_H=d_2[d_4];if(!d_g.isIn(d_k,d_H)){d_p=d_H;break;}else{d_4++;}}}for(var d_E= -1;++d_E<d_l;)d_h.move(d_k[d_E],d_p);d_h.fire('Items Reordered');d_h.d_5();}}d_h.d_6?d_h.confirm({state:'warning',title:d_h.localize('confirmDragToReorderTitle'),message:d_h.localize('confirmDragToReorderPrompt'),yesHandler:function(){d_h.d_6=d_c;d_h.fire('Drag Confirmed');d_1();},noHandler:function(){d_z.set({dragCancelled:true});}}):d_1();}}});d_h.wire('Item Mouse Down',function(d_0){if(d_h.d_7){d_i=d_0.source;d_z.mousedown(d_0.domEvent);}d_0.bubble=d_c;});}),d_8=d_g.prototype;d_8.d_9=function(d_ba){var d_h=this,d_bb=d_ba.properties,d_bc=d_h.makeItemWidgetName(d_bb),d_bd=d_h.getNode('itemTemplate');if(d_bd)d_ba.html=d_bd.innerHTML.replace(/ITEMWIDGETNAME/g,d_bc);
d_ba.built=d_c;d_ba.container=d_h.getNode('items');d_ba.insertionMode=d_h.d_F=='reverse'?'inner top':'inner bottom';d_h.get('items').push(d_bb);return d_h.addItemWidget(d_bc,d_ba);};d_8.d_5=function(){this.fire('Items Changed')};d_8.d_be=function(d_H){d_H.removeUi();d_H.kill();this.removeChild(d_H);};d_8.d_bf=function(){var d_h=this;d_h.forAll(function(d_H){d_h.d_be(d_H)});};var d_bg={selected:d_b};d_8.add=function(d_bh){var d_h=this,d_bi=[];if(d_h.isWired){if(!d_g.isArray(d_bh))d_bh=[d_bh];var d_bj=d_bh.length;if(d_bj){d_h.d_bk&&d_h.selectAll(d_c);var d_bl=d_h.d_bk?d_bg:d_d;for(var d_bm= -1;++d_bm<d_bj;)d_bi.push(d_h.d_9(d_g.copyInto(d_bh[d_bm],d_bl)));}d_h.d_5();}return d_bi;};d_8.getItemWidgetProperties=function(){var d_h=this;return(d_g.copyInto({previewTooltip:function(){return d_h.d_7?d_h.getNode('tooltipDragToReorder'):d_d}},d_h.get('itemWidgetProperties')));};d_8.finishRemove=function(d_bn,d_bo){var d_h=this,d_bp=d_h.get('items'),d_2=d_h.itemWidgets,d_3=d_2.length,d_bq=d_bn,d_br=d_bn.length;
if(d_br==d_3){d_h.d_bf();}else{d_bq=[];d_br=0;var d_bs=d_d;d_h.forAll(function(d_H,d_M){if(d_g.isIn(d_bn,d_H)){d_bs=d_d;d_bq.push(d_H);d_br++;d_h.d_be(d_H,d_M);}else{if(!d_bs&& !d_H.get('locked'))d_bs=d_H;if(d_br){d_bp[d_M-d_br]=d_bp[d_M];d_2[d_M-d_br]=d_H;}}});}if(d_br){d_bp.length=d_2.length=d_3-d_br;d_h.fire({name:'Items Removed',byUser:d_bo,totalBeforeRemove:d_3,itemWidgetsRemoved:d_bq,totalRemoved:d_br,percentRemoved:d_br/d_3*100});d_h.d_5();}};d_8.move=function(d_bt,d_bu){var d_h=this,d_bv=d_h.d_F=='reverse',d_bw=d_bu?d_bu.getNode():d_d,d_bp=d_h.get('items'),d_2=d_h.itemWidgets,d_bx=d_h.getNode('items'),d_by=d_bt.getNode(),d_bz=d_bv?(d_bw?d_bw.nextSibling:d_bx.childNodes[0]):d_bw;d_bz?d_bx.insertBefore(d_by,d_bz):d_bx.appendChild(d_by);var d_bA=d_g.indexIn(d_2,d_bt),d_bB=d_bp[d_bA];d_2.splice(d_bA,1);d_bp.splice(d_bA,1);var d_bC=d_bu?d_g.indexIn(d_2,d_bu):d_2.length-(d_bv?0:1);d_2.splice(d_bC,0,d_bt);d_bp.splice(d_bC,0,d_bB);};d_g.registerProperties({d_7:{name:'dragToReorder',value:d_c},d_6:{
name:'confirmToDrag',value:d_c},d_F:{name:'itemDisplayOrder',value:'normal'},d_bk:{name:'makeNewlyAddedSelected',value:d_b}});return d_g;}});