/*
	UIZE JAVASCRIPT FRAMEWORK 2010-01-24

	http://www.uize.com/reference/Uize.Data.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Data',builder:function(){var _a=function(){},_b=true,_c=false,_d=null;var _e={};_a.getColumn=function(_f,_g,_h){var _i=[];if(_f){var _j=_h?{}:_d;for(var _k= -1,_l=_f.length;++_k<_l;){var _m=_f[_k][_g];if(!_h||(!_j[_m]&&(_j[_m]=1)))_i.push(_m);}}return _i;};_a.findRecords=function(_n,_o){var _p=[];if(_n){for(var _q= -1,_r=_n.length,_s;++_q<_r;)Uize.recordMatches(_s=_n[_q],_o)&&_p.push(_s);}return _p;};_a.getKeys=function(_t){var _i=[];for(var _u in _t)_i.push(_u);return _i;};_a.getTotalKeys=function(_t){var _i=0;for(var _u in _t)_i++;return _i;};_a.getLookup=function(_v,_w){var _x={};if(arguments.length==1)_w=_b;for(var _y= -1,_z=_v.length;++_y<_z;)_x[_v[_y]]=_w;return _x;};_a.getReverseLookup=function(_t){var _x={};for(var _u in _t)_x[_t[_u]]=_u;return _x;};_a.getValues=function(_t){if(Uize.isArray(_t))return _t;var _i=[];for(var _u in _t)_i.push(_t[_u]);return _i;};_a.isEmpty=function(_t){if(_t&&typeof _t=='object'&&_t.constructor!=_e.constructor)_t=_t.valueOf();if(!_t)return _b;
if(Uize.isArray(_t))return!_t.length;if(typeof _t=='object'){for(var _u in _t)return _c;return _b;}return!_t;};_a.filter=function(_t,_A){var _B=this,_i={};if(_t&&_A){for(var _C= -1,_D=_A.length;++_C<_D;){var _E=_A[_C];if(_E in _t)_i[_E]=_t[_E];}}return _i;};_a.identical=function(_F,_G,_H){if(!_H)_H=_e;var _I=_H.equality,_J=_I=='loose',_K= !_J&&_I!='type',_L=_H.allowConjoined!==_c;function _M(_F,_G){var _N,_O=typeof _F,_P=_O==typeof _G,_Q=_O=='object';if(_P&&_Q&&_F&&_G){if(_F==_G){_N=_L;}else if(_N=(typeof _F.length=='number'?_F.length===_G.length:_b)&&_a.getTotalKeys(_F)==_a.getTotalKeys(_G)){for(var _E in _F){if(!(_E in _G)|| !_M(_F[_E],_G[_E])){_N=_c;break;}}}}else{_N=(_J?_F==_G:(_P&&(_K?_F===_G:(!_Q|| !_F== !_G))))||(_P&&_O=='number'&&isNaN(_F)&&isNaN(_G));}return _N;}return _M(_F,_G);};_a.conjoined=function(_F,_G){function _R(_t){var _S=[];function _T(_t){if(typeof _t=='object'){if(!Uize.isIn(_S,_t)){_S.push(_t);for(var _E in _t)_T(_t[_E]);}}}_T(_t);return _S;}var _U=_c,_V=_R(_F),_W=_V.length,_X=_R(_G);
for(var _Y= -1;++_Y<_W&& !_U;)_U=Uize.isIn(_X,_V[_Y]);return _U;};_a.clones=function(_F,_G){return(_a.identical(_F,_G,{allowConjoined:_c})&& !_a.conjoined(_F,_G));};_a.intersection=function(_F,_G){var _i={};if(_F&&_G){for(var _E in _F){var _Z=_F[_E];if(_G[_E]===_Z)_i[_E]=_Z;}}return _i;};_a.map=function(_0,_1,_2){if(typeof _1=='number'){_1=new Array(_1);if(typeof _2!='object')_2=_1;}var _3=Uize.isArray(_1);if(typeof _2!='object')_2=_2?_1:_3?[]:{};if(typeof _0=='string')_0=new Function('value','key','return '+_0);function _4(_u){var _5=_0.call(_1,_1[_u],_u);if(_2)_2[_u]=_5;}if(_3){for(var _6= -1,_7=_1.length;++_6<_7;)_4(_6);}else{for(var _u in _1)_4(_u);}return _2;};_a.min=function(_t){return Math.min.apply(0,_a.getValues(_t));};_a.max=function(_t){return Math.max.apply(0,_a.getValues(_t));};_a.reorderArray=function(_1,_8,_2){if(typeof _2!='object')_2=_2===_c?_1:[];if(_2!=_1)_2.length=0;if(_8=='inside out'||_8=='outside in'){if(_2==_1)_1=_1.concat();for(var _9=0,_ba=_1.length-1,_bb=_ba>>1,_bc=_8=='inside out',
_6=_bc?_bb+1: -1;_bc? --_6>=0: ++_6<=_bb;){_2[_9++]=_1[_6];if(_6!=_ba-_6)_2[_9++]=_1[_ba-_6];}}else{if(_2!=_1)Array.prototype.push.apply(_2,_1);if(_8!='normal')_8=='reverse'?_2.reverse():_2.sort(function(){return Math.random()*2-1});}return _2;};return _a;}});