/*
	UIZE JAVASCRIPT FRAMEWORK 2010-01-24

	http://www.uize.com/reference/Uize.Doc.Simple.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Doc.Simple',required:['Uize.Data.Simple','Uize.String','Uize.Templates.List'],builder:function(){var _a,_b='string',_c=function(){},_d={},_e=Uize.String.limitLength;var _f='[-\\*~:\\.]',_g=new RegExp(_f),_h=new RegExp('^\\s*'+_f+'\\s*$'),_i='([@#\\+a-zA-Z]|\\d+)',_j=new RegExp(_i),_k=new RegExp('^([<\\(\\{\\[]*\\s*'+_i+'?\\s*[>\\)\\}\\]]*\\s*'+_f+'*\\s+)'),_l={47:1,92:1};var _m=_c.build=function(_n){function _o(_p,_q){var _r=_n[_p];return typeof _r==_b?_r:_q;}var _s=_n.data,_t=_n.urlDictionary||_d,_u=_n.pathToRoot||'',_v=_o('indentChars','\t'),_w=_o('headingNumberingSeparator','. '),_x=_o('headingNumberingDelimiter','.'),_y=[0],_z=[0],_A=[],_B={items:[]};if(typeof _s==_b)_s=Uize.Data.Simple.parse({simple:_s,parseName:false});function _C(_s){var _D=_s.children;if(_D.length){var _E={};for(var _F= -1;++_F<_D.length;){var _G=_D[_F],_H=_G.children;if(_H.length){var _I=_G.value,_J=_E[_I];if(_J){_J.children=_J.children.concat(_H);_D.splice(_F,1);_F--;}else{_E[_I]=_G;}}}
for(var _F= -1,_K=_D.length;++_F<_K;)_C(_D[_F]);}}_n.canonicalizePeerSections!==false&&_C(_s);var _L=_n.sectionsToSort;if(_L){var _M=_L.length,_N={};for(var _O= -1;++_O<_M;)_N[_L[_O]]=1;function _P(_s){var _D=_s.children,_K=_D.length;if(_K){_N[_s.value]&&_D.sort(function(_Q,_R){return _Q.value<_R.value? -1:1});for(var _F= -1;++_F<_K;)_P(_D[_F]);}}_P(_s);}var _S={},_T=[0];function _U(_s,_V,_W){if(typeof _V!='number')_V=0;if(typeof _W!=_b)_W='';var _D=_s.children,_X=_s.value,_Y={};if(_D.length){_T[_V]++;var _Z=_V?(_W+(_W?'_':'')+_T[_V]):'';_S[_X]=_Z;_T[_V+1]=0;for(var _F= -1,_K=_D.length;++_F<_K;)_U(_D[_F],_V+1,_Z);}}_U(_s);function _0(_1,_2){function _3(_4,_5,_6,_7,_8){if(_2)return _5;var _9=_7=='url';if(_7&& !_9){if(_7=='text')_8=_5;var _ba=_S[_8];_ba?(_8='#'+_ba):((_8=_t[_8]||'')&&(_9=true));}if(_l[_8.charCodeAt(0)])_8=_u+_8.slice(1);return(_4+(_8?('<a href="'+_8+'"'+(_9&&/^[a-zA-Z]+:/.test(_8)?' target="_blank" class="externalSiteLink"':'')+'>'+_5+'</a>'):_5)+_6);}return(_1.replace(/^#(\S*)/,
function(_bb,_bc){return _3('<a name="'+_bc+'">','','</a>')}).replace(/\B\*.+?\*\B/g,function(_bb){return _3('<b>',_bb.slice(1,-1),'</b>','text')}).replace(/\b__.+?__\b/g,function(_bb){return _3('<b><i>',_bb.slice(2,-2),'</i></b>','text')}).replace(/\b_.+?_\b/g,function(_bb){return _3('<i>',_bb.slice(1,-1),'</i>','text')}).replace(/\B==.+?==\B/g,function(_bb){return _3('<code><b>',_bb.slice(2,-2),'</b></code>','text')}).replace(/\B=.+?=\B/g,function(_bb){return _3('<code>',_bb.slice(1,-1),'</code>','text')}).replace(/\B`.+?`\B/g,function(_bb){return _3('',_bb.slice(1,-1),'','text')}).replace(/\[\[(#.+?|[a-zA-Z]+:.+?|.+?\.(?:htm|html|jpg|gif|png)(?:[\?#][^\]]*)?)\]\[(.+?)\]\]/g,function(_bb,_bd,_be){return _3('',_be,'','url',_bd)}).replace(/\[\[(.+?)\]\[(.+?)\]\]/g,function(_bb,_bf,_be){return _3('',_be,'','section',_bf)}).replace(/\[\[(#.+?|[a-zA-Z]+?:.+?)\]\]/g,function(_bb,_bd){return _3('',_bd,'','url',_bd)}).replace(/\[\[(.+?)\]\]/g,function(_bb,_bf){return _3('',_bf,'','text')}));}function _bg(
_s,_V,_bh,_bi,_bj,_bk,_bl){function _bm(_bn){_A.push(_bi+_bn)}function _bo(_bp){var _bq=_V+ !!_bp;if(_z[_bq]){_bm((_bp?_v:'')+'</table>');_z[_bq]=0;}}var _D=_s.children,_X=_s.value,_br;if(!_D.length){if(/\r|\n|\r\n/.test(_X)){_bo();_bm('');_bm('<pre class="sample-code">'+_bs(_X)+'</pre>');_bm('');}else if(/^={3,}$/.test(_X)){_bo();_bm('<hr class="thick"/>');}else if(/^-{3,}$/.test(_X)){_bo();_bm('<hr class="thin"/>');}else if((_br=_X.match(_k))&&/[^\w\s\d]/.test(_br[1])){var _bt=_br[1],_bu=_bt.match(_j);_z[_V]||_bm('<table class="list">');if(_bu){var _bv=_bu[1],_bw='';if(/[#\+]|\d+/.test(_bv)){_bw=_z[_V]+1+'';}else if(/[@a-z]/i.test(_bv)){_bw='abcdefghijklmnopqrstuvwxyz'.charAt(_z[_V]);if(/[A-Z]/.test(_bv))_bw=_bw.toUpperCase();}_bt=_bt.replace(_j,_bw)}else{_bt=_h.test(_bt)?_bt.replace(_g,'<span class="bullet"></span>'):_bs(_bt);}_bm('<tr valign="top">'+'<td><span style="white-space:nowrap;">'+_bt+'</span></td>'+'<td>'+_0(_X.replace(_k,''))+'</td>'+'</tr>');_z[_V]++;}else{_bo();var _bx=_0(_X);
if(/[A-Z]/.test(_bx)&& !/[a-z]/.test(_bx))_bx='<span class="allCaps">'+_bx+'</span>';_bm('<p>'+_bx+'</p>');_bm('');}}else{_bo();_y[_V]++;var _by=_V>0,_bz=_by?(_bj+(_bj?'_':'')+_y[_V]):'',_bA=_bz.replace(/_/g,_x)+(_bz?_w:'')+_X,_bB=(_bk?(_bk+' -> '):'')+_bA,_bC=_by?((_bl?(_bl+_x):'')+'<a href="#'+_bz+'" title="'+_bB+'">'+_y[_V]+'</a>'):'',_bD={title:_bA||'Contents',description:_D[0].children.length?'':_e(_0(_D[0].value,true),400),link:_bz?('#'+_bz):'',items:[]};_bh.items.push(_bD);if(_X){var _bE='h'+Math.min(_V,5),_bF=_bC+_w;_bm('<a name="'+_bz+'"></a>');_bm('<'+_bE+' class="heading'+_V+'" title="'+_bB+'">'+(_bC?'<span class="headingNumber">'+_bF+'</span>':'')+_X+'</'+_bE+'>');}_bm('<div class="contents'+_V+'">');_y[_V+1]=_z[_V+1]=0;for(var _F= -1,_K=_D.length;++_F<_K;)_bg(_D[_F],_V+1,_bD,_bi+_v,_bz,_bB,_bC);_bo(true);/\S/.test(_A[_A.length-1])||_A.pop();_bm('</div>');_bm('');}}_bg(_s,0,_B,'','','','');var _bG=_B.items,_bH=(_n.contentsList!==false&&(_bG.length&&(_bG.length>1||_bG[0].items.length))?(
'<div id="page_contents" class="contents-tree-shell">\n'+Uize.Templates.List.process({items:_bG})+'\n'+'</div>\n'+'\n'):'')+_A.join('\n');return(_n.result=='full'?{html:_bH,contentsTreeItems:_bG}:_bH);};_c.toDocument=function(_bI){return _m({data:_bI})};var _bs=_c.toSampleCode=function(_bJ){return _bJ.replace(/\t/g,'  ').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');};return _c;}});