/*
	UIZE JAVASCRIPT FRAMEWORK 2010-01-24

	http://www.uize.com/reference/Uize.Widget.Dialog.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Widget.Dialog',required:['Uize.Node','Uize.Widget.Button','Uize.Widget.Drag','Uize.Fade'],builder:function(c_a){var c_b=true,c_c=false,c_d,c_e=Uize.Node,c_f=Uize.Widget,c_g=c_f.Drag;var c_h={},c_i={},c_j=0,c_k=navigator,c_l=c_k.appName=='Microsoft Internet Explorer'&&c_k.appVersion.indexOf('MSIE 6')> -1;var c_m=c_a.subclass(function(){var c_n=this;(c_n.c_o=c_n.shieldFade=new Uize.Fade({deceleration:1,duration:750})).wire('Changed.value',function(){c_n.set({c_p:+c_n.c_o})});c_n.wire({'Drag Start':function(c_q){if(!c_n.c_r){c_n.c_r=c_b;c_n.fire('First Drag Since Shown');c_n.c_s&&c_n.set({c_t:c_c});}},'Drag Done':function(){var c_u=c_e.getById(c_n.c_u);if(c_u){var c_v=c_e.getCoords(c_u),c_w=c_n.getNode();c_n.set({offsetX:parseInt(c_e.getStyle(c_w,'left'))-c_v.left,offsetY:parseInt(c_e.getStyle(c_w,'top'))-c_v.top})}}});},function(){var c_n=this;var c_w,c_x=[0,0];(c_n.c_y=c_n.addChild('drag',c_g,{cursor:'move'})).wire({'Before Drag Start':function(c_q){c_w=c_n.getNode();
c_x[0]=parseInt(c_e.getStyle(c_w,'left'));c_x[1]=parseInt(c_e.getStyle(c_w,'top'));},'Changed.inDrag':function(){c_n.set({c_z:c_n.c_y.get('inDrag')})},'Drag Start':c_n,'Drag Update':function(c_q){var c_A=c_n.c_y.eventDeltaPos;c_e.setStyle(c_w,{left:c_x[0]+c_A[0],top:c_x[1]+c_A[1]});},'Drag Done':c_n});function c_B(c_C){c_n.fire(c_C).abort||c_n.set({c_D:c_c});}c_n.c_E('close',function(){c_B('Close')});c_n.c_E('qualifiedOk',function(){c_B('Qualified Ok')});c_n.c_E('ok',function(){c_B('Ok')});c_n.c_E('cancel',function(){c_B('Cancel')});c_a.wire('Window Resized',function(){c_n.c_F()});c_n.c_G();c_n.atEndOfOmegaStructor();}),c_H=c_m.prototype;c_H.c_E=c_f.Button.addChildButton;var c_F=c_H.c_F=function(){var c_n=this;if(c_n.isWired&&c_n.c_D&& !c_n.c_z){c_g.resizeShield(c_n.getNode('shield'));if(c_n.c_I){var c_w=c_n.getNode(),c_u=c_e.getById(c_n.c_u);if(c_u){var c_v=c_e.getCoords(c_u);c_e.setStyle(c_w,{left:c_v.left+c_n.c_J,top:c_v.top+c_n.c_K});}else{c_e.centerInWindow(c_w);}}}};var c_L=c_H.c_L=function(){
var c_n=this;c_n.isWired&&c_n.c_D&& !c_n.c_z&&c_n.setNodeStyle('',{width:c_n.c_M,height:c_n.c_N});};c_H.c_O=function(){var c_n=this;c_n.isWired&&c_n.c_D&&c_n.setNodeOpacity('shield',c_n.c_p);};c_H.c_P=function(){var c_n=this;if(c_n.isWired){var c_Q=c_n.c_R||c_n.c_S;c_Q!=c_d&&c_n.setNodeInnerHtml('title',c_Q||'&nbsp;');}};var c_G=c_H.c_G=function(){var c_n=this,c_T=c_n.children;function c_U(c_V,c_W){c_V&&c_W!=c_d&&c_V.set({text:c_W});}c_U(c_T.ok,c_n.c_X||c_n.c_Y);c_U(c_T.cancel,c_n.c_Z||c_n.c_0);};c_H.atEndOfOmegaStructor=c_H.afterWireUi=function(){};c_H.updateUi=function(){this.c_P();};c_H.wireUi=function(){var c_n=this;if(!c_n.isWired){c_n.c_y.set({node:c_n.getNode('title')});function c_1(c_2,c_V,c_3){if(!c_n.get(c_2)){var c_4=(c_V.getNode(c_3)||c_h).innerHTML;c_4&&c_n.set(c_2,c_4);}}c_1('defaultTitle',c_n,'title');c_1('defaultOkText',c_n.children.ok,'text');c_1('defaultCancelText',c_n.children.cancel,'text');c_a.prototype.wireUi.call(c_n);c_n.afterWireUi();}};c_m.registerProperties({c_I:{
name:'autoPosition',value:c_b,onChange:c_F},c_Z:{name:'cancelText',onChange:c_G},c_p:{name:'currentShieldOpacity',onChange:c_H.c_O},c_0:{name:'defaultCancelText',onChange:c_G},c_Y:{name:'defaultOkText',onChange:c_G},c_S:{name:'defaultTitle',onChange:c_H.c_P},c_N:{name:'height',onChange:c_L},c_s:{name:'hideShieldOnDrag',value:c_b},c_z:{name:'inDrag',value:c_c},c_u:{name:'mooringNode',onChange:c_F},c_J:{name:'offsetX',onChange:c_F,value:0},c_K:{name:'offsetY',onChange:c_F,value:0},c_5:{name:'okEnabledOnShow',value:c_b},c_X:{name:'okText',onChange:c_G},c_6:{name:'shieldOpacity',onChange:function(){this.c_t&&this.set({c_p:this.c_6});},value:.3},c_t:{name:'shieldShown',onChange:function(){var c_n=this;if(c_n.isWired&&c_n.c_D){if(c_n.c_t){c_n.c_p=c_d;c_n.set({c_p:c_n.c_6});}else{c_n.c_o.start({startValue:c_n.c_6,endValue:.001});}}},value:c_c},c_D:{name:'shown',onChange:function(){var c_n=this;if(c_n.isWired){function c_7(){if(c_l){var c_w=c_n.getNode();c_e.doForAll(document.getElementsByTagName('select'),
function(c_8){c_e.show(c_8,!c_j||c_e.isOnNodeTree(c_8,c_w));});}}if(c_n.c_D){c_j++;c_n.c_r=c_c;typeof c_n.c_5=='boolean'&&c_n.children.ok.set({enabled:c_n.c_5?'inherit':c_c});c_n.fire('Before Show');c_n.setNodeStyle('',{position:'absolute'});var c_9= -1;for(var c_ba in c_i)c_9=Math.max(c_9,c_ba);c_i[c_n.c_ba= ++c_9]=1;c_n.setNodeStyle(['','shield'],{zIndex:4000+c_9*10});c_7();function c_bb(c_bc){c_n.showNode('',!c_bc);c_n.displayNode('',c_bc);}c_bb(c_b);c_n.c_L();c_n.c_F();c_bb(c_c);}else{c_j--;delete c_i[c_n.c_ba];c_7();c_n.fire('Before Hide');}c_n.set({c_t:c_n.c_D});c_n.displayNode(['','shield'],c_n.c_D);c_n.fire(c_n.c_D?'After Show':'After Hide');}},value:c_c},c_R:{name:'title',onChange:c_H.c_P},c_M:{name:'width',onChange:c_L}});return c_m;}});