/*______________
|       ______  |   B U I L T     O N     U I Z E     F R A M E W O R K
|     /      /  |   ---------------------------------------------------
|    /    O /   |   This JavaScript application is developed using the object
|   /    / /    |   oriented UIZE JavaScript framework as its foundation.
|  /    / /  /| |
| /____/ /__/_| |    ONLINE : http://www.uize.com
|          /___ |   LICENSE : Available under MIT License or GNU General Public License
|_______________|             http://www.uize.com/license.html
*/

/*______________
|       ______  |   U I Z E    J A V A S C R I P T    F R A M E W O R K
|     /      /  |   ---------------------------------------------------
|    /    O /   |    MODULE : UizeDotCom.Page.Home.library Library Module
|   /    / /    |
|  /    / /  /| |    ONLINE : http://www.uize.com
| /____/ /__/_| | COPYRIGHT : (c)2009-2010 UIZE
|          /___ |   LICENSE : Available under MIT License or GNU General Public License
|_______________|             http://www.uize.com/license.html
*/

/*?
	Introduction
		The =UizeDotCom.Page.Home.library= module is a library module that bundles together various JavaScript modules used by the very important homepage of the UIZE JavaScript Framework's Web site.

		*DEVELOPERS:* `Chris van Rensburg`
*/

Uize.module ({
	required:'UizeDotCom.Page.library',
	builder:function () {
		

Uize.module({name:'Uize.Fx.xTextShadow',required:'Uize.Color',builder:function(_a){var _b=function(){};for(var _c in{_d:1});_b._d=function(_e){var _f=[];for(var _g= -1,_h=_e.length,_i;++_g<_h;)_f.push((_i=_e[_g]).offsetX+_i.offsetXUnit+' '+_i.offsetY+_i.offsetYUnit+('blurRadius'in _i?(' '+_i.blurRadius+_i.blurRadiusUnit):'')+('color'in _i?(' '+Uize.Color.to(_i.color,'#hex')):''));return _f.join(',');};_a.defineStylePropertiesProfile({test:'textShadow',decoder:function(_e){if(Uize.isArray(_e))_e=_e.join(',');var _j=[],_k='(#[0-9a-f]{1,6}|(?:rgba?|hsla?)\\s*\\(.+?\\)|[a-z]+)?',_l='(?:(-?(?:\\d\\.?|\\.\\d)\\d*)(em|ex|px|in|cm|mm|pt|pc|))',_m='\\s+',_n='\\s*',_o=new RegExp('(?:^|)'+_n+'(?:'+_k+_m+_l+_m+_l+'(?:'+_m+_l+')?'+'|'+_l+_m+_l+'(?:'+_m+_l+')?'+'(?:'+_m+_k+')?'+')'+_n+'(?:$|,)','g'),_p;while(_p=_o.exec(_e)){var _q=_p[8],_r=_q?8:2,_i={offsetX:+_p[_r],offsetXUnit:_p[_r+1]||'px',offsetY:+_p[_r+2],offsetYUnit:_p[_r+3]||'px'},_s=_p[_q?14:1],_t=_p[_r+4];if(_s)_i.color=Uize.Color.to(_s,'RGB array');if(_t){
_i.blurRadius= +_t;_i.blurRadiusUnit=_p[_r+5]||'px';}_j.push(_i);}return _j;},encoderExpression:'Uize.Fx.xTextShadow.'+_c+'(VALUE)'});return _b;}});


Uize.module({name:'Uize.Widget.HoverFader',required:['Uize.Fx','Uize.Fade.xFactory','Uize.Node'],builder:function(c_a){var c_b=c_a.subclass(),c_c=c_b.prototype;c_c.c_d=function(c_e,c_f,c_g){c_f!=(c_g.reverse||false)?Uize.Fx.fadeStyle(c_e,this.c_h,this.c_i,0,c_g):Uize.Fx.fadeStyle(c_e,this.c_i,this.c_h,0,c_g);};c_c.c_j=function(c_e){this.c_d(c_e,true,this.c_k);};c_c.c_l=function(c_e){this.c_d(c_e,false,this.c_m);};c_c.tickle=function(c_g){var c_n=this;if(c_n.isWired){var c_o=c_n.c_o,c_p=c_o.length-1,c_q;Uize.Fade.fade(function(c_r){if(c_q==null)c_q=c_r-1;var c_s=c_r>c_q?1: -1;while(c_q!=c_r)c_n.c_l(c_o[c_q+=c_s]);},0,c_p,0,c_g==null||typeof c_g!='object'?{quantization:1,duration:c_p*(c_g==null?100:c_g)}:c_b.copyInto({quantization:1,duration:750},c_g));}};c_c.wireUi=function(){var c_n=this,c_o=c_n.c_o;if(!c_n.isWired&&c_o){c_n.wireNode(c_n.c_o=Uize.Node.find(c_o),{mouseover:function(){c_n.c_j(this)},mouseout:function(){c_n.c_l(this)}});c_a.prototype.wireUi.call(c_n);}};function c_t(){var c_u=this.c_u;
this.c_k=c_u?c_b.copyInto({},c_u,this.c_v):this.c_v;this.c_m=c_u?c_b.copyInto({},c_u,{reverse:!c_u.reverse},this.c_w):this.c_w;}c_b.registerProperties({c_h:{name:'defaultStyle',value:{color:'fff',backgroundColor:'000'}},c_v:{name:'fadeIn',onChange:c_t,value:{duration:250}},c_u:{name:'fadeInOut',onChange:c_t},c_w:{name:'fadeOut',onChange:c_t,value:{duration:350}},c_i:{name:'hoverStyle',value:{color:'000',backgroundColor:'fff'}},c_o:'nodes'});return c_b;}});


Uize.module({name:'Uize.Json',builder:function(){var _a=function(){},_b,_c=true,_d=false,_e='string',_f={};var _g='       ',_h=_g.replace(/ /g,_g).replace(/ /g,_g),_i={'break':1,'boolean':1,'case':1,'catch':1,'continue':1,'const':1,'debugger':1,'default':1,'delete':1,'do':1,'else':1,'export':1,'false':1,'finally':1,'for':1,'function':1,'if':1,'import':1,'in':1,'instanceof':1,'new':1,'null':1,'return':1,'switch':1,'this':1,'throw':1,'true':1,'try':1,'typeof':1,'var':1,'void':1,'while':1,'with':1};_a.from=function(_j){var d;return eval('d='+(_j||'null'));};_a.to=function(_k,_l){_l=_l?(_l=='mini'?{indentChars:'',linebreakChars:''}:_l):_f;function _m(_n,_o){var _p=_l[_n];return typeof _p==_e?_p:_o;}var _q=[],_r=_m('indentChars','\t'),_s=_m('linebreakChars','\n'),_t=_m('quoteChar','\''),_u=new RegExp(_t,'g'),_v='\\'+_t,_w=_l.sortKeys===true,_x=_l.padKeys===true,_y=_l.keyDelimiter||':',_z={left:0,center:0.5,right:1}[_l.keyAlign||'left'],_A=_l.whenToQuoteKeys||'auto';function _B(_C){return _h.substr(0,_C)}
function _D(_e){return(_t+_e.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/\r/g,'\\r').replace(_u,_v)+_t);}function _E(_F,_G,_H,_I){var _J=0,_K=typeof _F;function _L(_M,_I){_q.push(_H+(_J++ ?'':_G)+_M+(_I?',':''));}if(_F==_b||_K=='number'||_K=='boolean'){_L(_F,_I);}else if(_K==_e){_L(_D(_F),_I);}else if(_F instanceof RegExp){_L(_F.toString(),_I);}else if(_F instanceof Date){_L('new Date ('+ +_F+')',_I);}else if(_K=='object'){var _N=_H+_r;if(_F instanceof Array||(_F&&typeof _F.splice=='function')){var _O=_F.length;if(_O){var _P=_O-1;_L('[');for(var _Q= -1;++_Q<_O;)_E(_F[_Q],'',_N,_Q<_P);_L(']',_I);}else{_L('[]',_I);}}else{var _R=[];for(var _S in _F)_R.push(_S);var _T=_R.length;if(_T){_w&&_R.sort();function _U(_V){return(isNaN(+_V)?(/[^\w\$]|^\d/.test(_V)||_i[_V]):_V!= +_V+''||_V<0);}var _W=_A=='always';if(!_W&&_A=='auto all'){for(var _X= -1;++_X<_T&& !_W;)_W=_W||_U(_R[_X]);}var _Y=[];for(var _X= -1;++_X<_T;){var _V=_R[_X];_Y[_X]=(_W||_U(_V))?_D(_V):_V;}var _Z=0;if(_x){for(var _X= -1;++_X<_T;)
_Z=Math.max(_Z,_Y[_X].length);}var _0=_T-1;_L('{');for(var _X= -1;++_X<_T;){var _1='',_2=_Y[_X];if(_x){var _3=_Z-_2.length,_4=Math.round(_z*_3);_1=_B(_4);_2+=_B(_3-_4);}_E(_F[_R[_X]],_2+_y,_N+_1,_X<_0);}_L('}',_I);}else{_L('{}',_I);}}}}_E(_k,'','');return _q.join(_s);};return _a;}});


Uize.module({name:'Uize.String',builder:function(){var _a=function(){},_b;var _c=[],_d=new RegExp('[^ \\n\\r\\t\\f\\x0b\\xa0\\u2000\\u2001\\u2002\\u2003\\u2004\\u2005\\u2006\\u2007\\u2008\\u2009\\u200a\\u200b\\u2028\\u2029\\u3000]'),_e={9:1,10:1,11:1,12:1,13:1,32:1,160:1,8192:1,8193:1,8194:1,8195:1,8196:1,8197:1,8198:1,8199:1,8200:1,8201:1,8202:1,8203:1,8232:1,8233:1,12288:1};var _f,_g;function _h(_i){if(!_g)_g=(_f='          '.replace(/ /g,'          ')).length;if(_i>_g)_g=(_f=_j(_f,Math.floor(_i/_g))+_f.substr(0,_i%_g)).length;return _f.substr(0,_i);}function _k(_l,_m,_n){if(!_m)return true;var _o=_l.length,_p=_m.length,_q=_n?_o-_p:0,_r=_q+_p-1;return(_p<=_o&&_l.charCodeAt(_q)==_m.charCodeAt(0)&&(_p==1||(_l.charCodeAt(_r)==_m.charCodeAt(_p-1)&&(_p==2||(_p==_o?_m==_l:_n?_l.indexOf(_m,_q)==_q:_l.lastIndexOf(_m,_r)==0)))));}_a.contains=function(_l,_m){return(_m.length<=_l.length&&(_a.startsWith(_l,_m)||_a.endsWith(_l,_m)||_l.indexOf(_m)> -1));};_a.endsWith=function(_l,_m){return _k(_l,_m,true);};
var _s=_a.hasPadding=function(_l){var _o=_l.length;return!!(_o&&(_e[_l.charCodeAt(0)]||_e[_l.charCodeAt(_o-1)]));};_a.hugJoin=function(_t,_u,_v,_w){return(_t.length?(''+_u+_t.join(''+_v+(_w!=_b?_w:'')+_u)+_v):'');};_a.joinUsingSuffixPriority=function(_u,_v,_x){var _y=_v.length;return(_x<_y?_v.substr(0,_x):_x==_y?_v:_z(_u,_x-_y)+_v);};var _z=_a.limitLength=function(_l,_x){var _A='...',_B=_A.length;return(_x<1?'':_x<=_B?_l.slice(0,_x):_l.length>_x?(_l.substr(0,_x-_B)+_A):_l);};var _C=[],_j=_a.repeat=function(_l,_D){if(_D<1|| !_l)return'';if(_D==1)return _l;if(_l==' ')return _h(_D);_C.length=_D+1;return _C.join(_l);};_a.splitInTwo=function(_l,_E){if(_E instanceof RegExp)_E=(_l.match(_E)||_c)[0];var _F=_E!=_b?_l.indexOf(_E): -1;return(_F> -1?[_l.substr(0,_F),_l.substr(_F+_E.length)]:[_l,'']);};_a.startsWith=_k;_a.toCamel=function(_G,_H){return((Uize.isArray(_G)?_G.join(' '):_G).toLowerCase().replace(/^\W+/,'').replace(/\W+$/,'').replace(_H?/(^|\W+)./g:/\W+./g,function(_I){return _I.slice(-1).toUpperCase()}));};
_a.trim=function(_l,_J){if(!_s(_l))return _l;var _K=_J==1?0:_l.search(_d),_L=_l.length-1;if(_K== -1)return'';if(_J!= -1)while(_e[_l.charCodeAt(_L)])_L--;return _l.slice(_K,_L+1);};_a.trimLeft=function(_l){return _a.trim(_l,-1);};_a.trimRight=function(_l){return _a.trim(_l,1);};return _a;}});


Uize.module({name:'Uize.Template',required:['Uize.Url','Uize.Json','Uize.String'],builder:function(){var _a=function(){},_b=true,_c=false,_d='string',_e=Uize.Url,_f=Uize.Json,_g=Uize.String,_h=_g.splitInTwo,_i=_g.trim;var _j={},_k=/^\s*=/,_l=/^\s*@/,_m=/^\s*\./,_n=/^!\s*/,_o=/(\r|\n|\r\n)[ \t]*$/,_p=/^[ \t]*(\r|\n|\r\n)[ \t]*/,_q='->';_a.compile=function(_r,_s){function _t(_d,_u){return(_u+_d.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/\r/g,'\\r').replace(new RegExp(_u,'g'),'\\'+_u)+_u);}_s=_s||_j;var _v=[],_w={},_x=_s.openerToken||'<%',_y=_s.closerToken||'%>',_z=_s.gobbleWhitespace!==_c,_A=_r.length,_B='var output = [];',_C='return output.join (\'\');',_D=[_B],_E=[],_F=0,_G,_H=_b,_I,_J,_K,_L,_M;function _N(_J){if(_E.length){_D.push('output.push ('+_E.join(',')+');');_E=[];}_D.push(_J);}function required(_O){Array.prototype.push.apply(_v,Uize.isArray(_O)?_O:[_O]);}function input(_P){Uize.copyInto(_w,_P);}function startBlock(_Q,_R){_N('function '+_Q+' ('+(_R||'')+') {'+_B);}function endBlock(){
_N(_C+'}');}while(_H){_G=_r.indexOf(_x,_F);if(_G<0)_G=_A;_I=_r.slice(_F,_G);_H=_G<_A;if(_H){_G+=2;_F=_r.indexOf(_y,_G);_J=_r.slice(_G,_F);_L=_k.test(_J);_M=_L||_m.test(_J);_K= !_M&&_l.test(_J);_F+=2;}if(_I){if(_z&&_H&& !_M&&_o.test(_I)&&_p.test(_r.substr(_F)))_I=_I.replace(_o,'');_I&&_E.push(_t(_I,'\''));;}if(_H){if(_M){_J=_L?_J.replace(_k,''):('input'+_J);var _S=_h(_J,_q),_T=_i(_S[0]),_U=_S[1];if(_U){_U=_U.split(_q);for(var _V= -1,_W=_U.length;++_V<_W;){var _X=_h(_U[_V],'{'),_Y=_i(_X[0]);if(_Y){var _Z=_i(_X[1]),_0=_n.test(_Y),_1=(_0?'de':'en')+'coder';if(_0)_Y=_Y.replace(_n,'');_T='Uize.Template.'+_1+'s.'+_Y+'.'+_1+'('+_T+(_Z?(',{'+_Z):'')+')';}}}_E.push(_T);}else if(_K){eval(_J.replace(_l,''));}else{_N(_J);}}}_N(_C);var _2=_D.join('\n'),_3=new Function('input',_2);return(_s.result=='full'?{input:_w,required:_v,code:_2,templateFunction:_3}:_3);};function _4(_5,_6,_7){var _8=_5,_9=_a[_7?'encoders':'decoders'],_ba=_7?'encoder':'decoder';function _bb(_6){var _bc=typeof _6==_d;if(_bc&&_6.indexOf('|')> -1){
_bb(_6.split('|'));}else{if(!_bc&&Uize.isArray(_6)){for(var _V= -1,_bd=_6.length;++_V<_bd;)_bb(_6[_7?_V:_bd-1-_V]);}else{var _be=_9[_bc?_6:_6.type][_ba];if(_be)_8=_be(_8,_bc?_j:_6);}}}_bb(_6);return _8;};_a.encode=function(_bf,_6){return _4(_bf,_6,_b)};_a.decode=function(_bg,_6){return _4(_bg,_6)};_a.encoders={json:{encoder:_f.to},miniJson:{encoder:function(_bf){return _f.to(_bf,'mini')}},url:{encoder:_e.resolve},urlParams:{encoder:_e.toParams},urlPiece:{encoder:_e.toPiece}};_a.decoders={json:{decoder:_f.from},miniJson:{decoder:_f.from},urlParams:{decoder:_e.fromParams},urlPiece:{decoder:_e.fromPiece}};return _a;}});


Uize.module({name:'Uize.Tooltip',required:['Uize.Node','Uize.Fade'],builder:function(){var _a=function(){},_b=true,_c=false,_d=Uize.Node;var _e=Uize.getGuid(),_f=[],_g,_h=16;function _i(){_d.setAbsPos(_g,_d.getEventAbsPos(),_h);}function _j(_k){if(_k!=_g){if(_k){if(_g){_l.stop();_m();}_d.wire(document.body,'scroll',_i,_e);_d.wire(document.documentElement,'mousemove',_i,_e);_g=_k;_d.setStyle(_g,{position:'absolute',zIndex:5000,left:-50000,top:-50000});_d.display(_g);_i();}else{_l.get('duration')>0?_l.start():_m();}}else if(_k){_l.stop();_d.setOpacity(_g,1);}}_a.showTooltip=function(_k,_n){if(_k=_d.getById(typeof _k=='function'?_k():_k)){if(_n!==_c){_f.push(_k);}else{var _o=Uize.indexIn(_f,_k,_b);_o> -1&&_f.splice(_o,1);}_j(_f[_f.length-1]);}};_a.hideTooltip=function(_p){_a.showTooltip(_p,_c)};var _l=_a.fade=new Uize.Fade({duration:0});function _m(){_d.unwireEventsByOwnerId(_e);_d.display(_g,_c);_d.setOpacity(_g,1);_g=null;}_l.wire({'Changed.value':function(){_d.setOpacity(_g,1-_l.get('progress'))},Done:_m});
return _a;}});


Uize.module({name:'Uize.Widget.AutoTooltip',required:['Uize.Tooltip','Uize.String'],builder:function(c_a){var c_b,c_c='auto',c_d='title';var c_e=c_a.subclass(),c_f=c_e.prototype;c_f.c_g=function(){var c_h=this;if(c_h.isWired){var c_i=c_h.c_i;c_i&&c_h.buildHtml(c_i);Uize.Tooltip.showTooltip(c_h.getNode(),!!c_i);}};c_f.c_j=function(){var c_h=this,c_k={},c_l={};if(c_h.isWired){c_h.wireNode(c_h.c_m=Uize.Node.find(c_h.c_m),{mouseover:function(){var c_n=this,c_o=c_n.id||(c_n.id=Uize.getGuid()),c_p=c_k[c_o];if(c_p===c_b){var c_q=c_h.c_q;if(c_q==c_c)c_q=c_n.title?c_d:'alt';var c_r=c_n.getAttribute(c_q);c_p=c_k[c_o]=c_r?c_h.c_s(c_r):null;if(c_p&&c_q==c_d)c_l[c_o]=c_n.title;}if(c_l[c_o])c_n.title='';c_h.set({c_i:c_p});},mouseout:function(){var c_n=this,c_t=c_l[c_n.id];if(c_t)c_n.title=c_t;c_h.set({c_i:null});}});}};c_f.updateUi=function(){this.c_g();};c_f.wireUi=function(){var c_h=this;if(!c_h.isWired){c_a.prototype.wireUi.call(c_h);c_h.c_j();}};c_e.registerProperties({c_i:{name:'data',onChange:c_f.c_g},c_q:{
name:'dataAttribute',value:'auto'},c_s:{name:'dataDecoder',value:function(c_u){var c_v={},c_w=[],c_x=/(([A-Z0-9 ]+:.+?)((\s*\|\s*)|$))([A-Z ]+:|$)/,c_y=this.c_y||function(c_z){return c_z};while(c_u){var c_A=c_u.match(c_x)||c_w,c_B=c_A[2];if(c_B){var c_C=Uize.String.splitInTwo(c_B,/\s*:\s*/);c_v[c_y(c_C[0])]=c_C[1];c_u=c_u.substr(c_A[1].length);}else{c_u='';}}return c_v;}},c_y:{name:'dataKeyTransformer',value:Uize.String.toCamel},c_m:{name:'nodes',onChange:c_f.c_j}});return c_e;}});


Uize.module({name:'Uize.Widget.Button',required:'Uize.Node',builder:function(c_a){var c_b,c_c=true,c_d=false,c_e=Uize.Node;var c_f=c_a.subclass(),c_g=c_f.prototype;var c_h,c_i={},c_j={grayed:16,'':8,over:4,active:2,playing:1},c_k='(Grayed|Over|Active|Playing)',c_l=new RegExp(c_k),c_m=new RegExp('(?:(?:(\\S+)\\s+\\1'+c_k+'))','g'),c_n=new RegExp('\\S*'+c_k+'\\b','g'),c_o=/\b(disabled|over|active|playing)\b/,c_p={},c_q={mouseover:['over','Over'],mouseout:['','Out'],mousedown:['down','Down'],mouseup:['over','Up'],click:['over','Click']};c_g.c_r=c_d;c_g.c_s=function(){return(this.get('enabledInherited')&& !this.get('busyInherited')&&(!this.c_t||this.c_u));};c_g.c_v=function(){this.c_w!=c_b&&this.isWired&&this.setNodeInnerHtml('text',this.c_w);};var c_x=c_g.c_x=function(){var c_y=this;if(c_y.isWired){var c_z=c_y.c_z,c_A=c_y.get('enabledInherited'),c_B=c_y.get('busyInherited'),c_C=(!c_A?16:0)|(!c_y.c_D||c_B?8:0)|(c_y==c_h?4:0)|(c_y.c_D=='down'||c_y.c_t?2:0)|(c_y.c_E?1:0),c_F=c_y.c_G[c_C];if(c_F==c_b){for(var
 c_H= -1,c_I=c_y.c_I,c_J=c_I.length;++c_H<c_J;){var c_K=c_I[c_H];if(c_C&c_j[c_K]){c_F=c_K;break;}}c_y.c_G[c_C]=c_F;}if(c_y.c_L=='classes'){var c_M=c_z.className,c_N='';if(c_y.c_O=='disambiguated'){var c_P=c_y.c_P;if(c_P==c_b){var c_Q=c_M.match(c_m);if(c_Q){c_P=c_Q[c_Q.length-1].split(' ',2)[0];}else{c_Q=c_M.replace(c_n,'').match(/(\S+)\s*$/);if(c_Q)c_P=c_Q[c_Q.length-1];}if(c_y.c_P=c_P=c_P||'')c_y.c_R=c_p[c_P]||(c_p[c_P]=new RegExp(c_P+'(\\s+'+c_P+c_k+')?'));}var c_S=c_F?' '+c_P+c_f.capFirstChar(c_F):'';c_N=c_P?c_M.replace(c_y.c_R,c_P+c_S):c_M.replace(c_l,'')+c_S;}else{var c_T=c_F=='grayed'?'disabled':c_F;c_N=c_o.test(c_M)?c_M.replace(c_o,c_T):c_M+(c_T?' ':'')+c_T;}if(c_N!=c_M)c_z.className=c_N;}else if(c_y.c_L=='frames'){c_y.c_U.style.top='-'+(c_y.c_V.c_W[c_F]*c_y.c_X.height)+'px';}if(c_y.c_Y&&Uize.Tooltip){var c_Z=c_y.c_D=='over'&&c_A&& !c_y.c_t;c_Z!=c_y.c_r&&Uize.Tooltip.showTooltip(c_y.c_Y,c_y.c_r=c_Z);}c_y.get('busyInherited')?c_e.setStyle(c_z,{cursor:'wait'}):c_e.showClickable(c_z,c_y.c_s());}};
c_g.c_0=function(c_1){var c_y=this;if(c_y.isWired){var c_2=c_1.type,c_3=c_2=='click',c_s=c_y.c_s();if(!c_y.c_4){c_y.c_4=c_c;function c_0(c_1){c_y.c_0(c_1)}c_y.wireNode(c_y.c_z,{mouseout:c_0,mousedown:c_0,mouseup:c_0});}if(c_3)c_1.cancelBubble=c_c;if(c_s){var c_5=c_q[c_2];c_y.set({c_D:c_5[0]});c_y.fire({name:c_5[1],domEvent:c_1});}}};c_g.updateUi=function(){this.c_x();this.c_v();};c_g.wireUi=function(){var c_y=this;if(!c_y.isWired){c_y.c_U=c_b;var c_z=c_y.c_z=c_y.getNode();if(c_z){var c_6=c_z.childNodes;if(c_6.length&&(c_6.length>1||c_6[0].nodeType!=3)&&(c_y.c_U=c_y.getNode('frames'))){c_y.c_L='frames';c_y.c_X=c_e.getDimensions(c_y.c_U.parentNode);}if(c_y.c_7&&c_z.tagName=='A'&& !c_z.onclick)c_z.onclick=c_e.returnTrue;function c_0(c_1){c_y.c_0(c_1)}c_y.wireNode(c_z,{mouseover:c_0,click:c_0});function c_x(){c_y.c_x()}c_y.wire({'Changed.busyInherited':c_x,'Changed.enabledInherited':c_x});c_a.prototype.wireUi.call(c_y);}}};c_f.addChildButton=function(c_8,c_9){var c_y=this,c_ba;function c_bb(){c_ba.wire('Click',
function(c_bc){if(c_9)typeof c_9=='string'?c_y.fire(c_9):c_9(c_bc);c_y.fire(c_bc);});}if(c_y==c_f){c_ba=new c_f({idPrefix:c_8,name:c_8,c_7:c_c});c_bb();(window[c_ba.instanceId]=c_ba).wireUi();}else{c_ba=c_y.children[c_8];if(!c_ba){c_ba=c_y.addChild(c_8,c_f);c_bb();}}return c_ba;};c_f.registerProperties({c_u:{name:'clickToDeselect',onChange:c_x,value:c_d},c_O:{name:'classNamingForStates',value:'disambiguated'},c_V:{name:'frameOrder',onChange:function(){var c_V=this.c_V;if(!c_V.c_W){for(var c_bd= -1,c_be=c_V.length,c_W=c_V.c_W={};++c_bd<c_be;)c_W[c_V[c_bd]]=c_bd;}},value:['grayed','','over','active','playing']},c_7:{name:'followLink',value:c_d},c_L:{name:'mode',value:'classes'},c_E:{name:'playing',onChange:c_x,value:c_d},c_t:{name:'selected',onChange:c_x,value:c_d},c_D:{name:'state',onChange:function(){var c_y=this;if(!c_y.c_D){if(c_h==c_y)c_h=c_b;}else if(c_y.c_D=='over'){c_h&&c_h!=c_y&&c_h.set({c_D:''});c_h=c_y;}c_y.isWired&&c_y.c_x();},value:''},c_I:{name:'statePrecedence',onChange:function(){var c_y=this,
c_bf=c_y.c_I.c_bg||(c_y.c_I.c_bg=c_y.c_I.join(','));c_y.c_G=c_i[c_bf]||(c_i[c_bf]={});c_y.isWired&&c_y.c_x();},value:['playing','active','grayed','over','']},c_w:{name:'text',onChange:c_g.c_v},c_Y:'tooltip'});return c_f;}});


Uize.module({name:'Uize.Widget.Scrolly',required:['Uize.Fade','Uize.Widget.Button'],builder:function(c_a){var c_b=true,c_c=false;var c_d=c_a.subclass(function(){var c_e=this;c_e.fade=new Uize.Fade({duration:400,acceleration:0,deceleration:1,quantization:1});c_e.fade.wire('Changed.value',function(){c_e.isWired&&c_e.setNodeProperties('view',c_e.fade.valueOf());});},function(){var c_e=this;function c_f(c_g,c_h,c_i){c_e.c_j(c_g,function(c_k){var c_l=c_k.domEvent.shiftKey?Infinity:1,c_m={};if(c_h)c_m.c_n=c_e.c_n+c_h*c_l;if(c_i)c_m.c_o=c_e.c_o+c_i*c_l;c_e.set(c_m);})}c_f('left',-1,0);c_f('right',1,0);c_f('up',0,-1);c_f('down',0,1);}),c_p=c_d.prototype;c_p.c_j=Uize.Widget.Button.addChildButton;c_p.c_q=function(c_r,c_s,c_t){var c_e=this;c_e.isWired&&c_e.displayNode([c_e.children[c_s].getNode(),c_e.children[c_t].getNode()],c_e.c_u||c_e.get('isScrollable'+c_r));};c_p.c_v=function(c_w){if(this.isWired){var c_x=this.getNode('view'),c_y=c_w=='X'?'Width':'Height';this.set('maxPage'+c_w,c_x?Math.max(
Math.ceil(c_x['scroll'+c_y]/c_x['offset'+c_y])-1,0):0);}};c_p.c_z=function(c_A,c_w){this.c_v(c_w);return(c_d.isNumber(c_A= +c_A)?c_d.constrain(c_A,0,this.get('maxPage'+c_w)||0):this.get('page'+c_w));};c_p.c_B=function(c_w){var c_C=this.get('page'+c_w),c_D=this.children;function c_E(c_g,c_F){var c_G=c_D[c_g];c_G&&c_G.set({enabled:c_F?'inherit':c_c});}c_E(c_w=='X'?'left':'up',c_C);c_E(c_w=='X'?'right':'down',(this.get('maxPage'+c_w)-c_C+1||2)>1);};c_p.updateUi=function(){this.c_v('X');this.c_v('Y');};function c_H(){var c_e=this;if(c_e.isWired){var c_x=c_e.getNode('view');c_e.fade.start({startValue:{scrollLeft:c_x.scrollLeft,scrollTop:c_x.scrollTop},endValue:{scrollLeft:c_e.c_n*c_x.offsetWidth,scrollTop:c_e.c_o*c_x.offsetHeight}});}}function c_I(){this.c_B('X')}function c_J(){this.c_B('Y')}function c_K(){this.c_q('X','left','right')}function c_L(){this.c_q('Y','up','down')}c_d.registerProperties({c_M:{name:'isScrollableX',onChange:c_K,value:c_c},c_N:{name:'isScrollableY',onChange:c_L,value:c_c},c_O:{
name:'maxPageX',onChange:[function(){this.set({c_M:(this.c_O+1||2)>1});},c_I]},c_P:{name:'maxPageY',onChange:[function(){this.set({c_N:(this.c_P+1||2)>1});},c_J]},c_n:{name:'pageX',conformer:function(c_Q){return this.c_z(c_Q,'X')},onChange:[c_H,c_I],value:0},c_o:{name:'pageY',conformer:function(c_Q){return this.c_z(c_Q,'Y')},onChange:[c_H,c_J],value:0},c_u:{name:'showButtonsWhenNotScrollable',onChange:[c_K,c_L],value:c_b}});return c_d;}});


Uize.module({name:'UizeDotCom.Page.Home',required:['Uize.Node.Event','Uize.Widget.HoverFader','Uize.Widget.Scrolly','Uize.Widget.AutoTooltip','Uize.Template','Uize.Fx','Uize.Fx.xTextShadow','Uize.Curve','Uize.Curve.Rubber'],builder:function(e_a){var e_b=e_a.subclass(null,function(){var e_c=this;e_c.addChild('demosScrolly',Uize.Widget.Scrolly).fade.set({curve:Uize.Curve.Rubber.easeOutBounce(3,.5),duration:1000});e_c.addChild('demoInfoTooltip',Uize.Widget.AutoTooltip,{nodes:{className:/\bdemosItem\b/},html:true});e_c.addChild(
'borderHoverFader',Uize.Widget.HoverFader,{nodes:{className:/\b(subPod|demosItem)\b/},defaultStyle:{borderColor:'000'},hoverStyle:{borderColor:'f'},fadeIn:{duration:800,curve:{borderColor:[Uize.Curve.easeOutPow(9),Uize.Curve.easeInPow(2),Uize.Curve.easeInPow(6)]}},fadeOut:{duration:1200,curve:{borderColor:[Uize.Curve.easeOutPow(4),null,Uize.Curve.easeInPow(3)]}}});e_c.addChild('podHeadingHoverFader',Uize.Widget.HoverFader,{nodes:{className:/\bpodHeading\b/},defaultStyle:{textShadow:['0em 0em 0em #0','0em 0em 0em #0','0em 0em 0em #0','0em 0em 0em #0'].join(',')},hoverStyle:{textShadow:['-1.5em 0em 1.5em #f','1.5em 0em 1.5em #f','0em -.3em 1.5em #abc','0em .3em 1em #def'].join(',')},fadeIn:{duration:700,curve:{textShadow:Uize.Curve.easeOutPow(4)}},fadeOut:{duration:1800,curve:{textShadow:Uize.Curve.easeInOutPow(2)}}});}),e_d=e_b.prototype;e_d.wireUi=function(){var e_c=this;if(!e_c.isWired){page.wireNode(Uize.Node.find({tagName:'A',self:function(){return!this.target&&this.getAttribute('href')!='javascript://'}
}),'click',function(e_e){page.launchPopup({url:this.href,width:895,height:595,name:'newWindow'});Uize.Node.Event.abort(e_e);});e_a.prototype.wireUi.call(e_c);Uize.Fx.fadeStyle(page.getNode('mantleImage'),{opacity:.01,clip:[50,450,50,450]},{opacity:1,clip:[0,900,100,0]},2000,{curve:Uize.Curve.easeInOutPow(4)});}};e_b.set({showFooter:false,showShareThisPanel:false});return e_b;}});
		Uize.module ({name:'UizeDotCom.Page.Home.library'});
	}
});

