/*
	UIZE JAVASCRIPT FRAMEWORK 2010-01-24

	http://www.uize.com/reference/Uize.Color.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Color',builder:function(){var _a;var _b,_c=/(\w+)\s*\(\s*([^,\)]+)\s*,\s*([^,\)]+)\s*,\s*([^,\)]+)\s*\)/i;function _d(_e){return Uize.constrain(Math.round(_e),0,255)||0;}function _f(_g){var _h;for(var _i in _g)(_h=_g[_i])in _b||(_b[_h]=_i);}var _j=function(){this.tuple=[];_k.from.apply(this,arguments);},_k=_j.prototype;_j.RgbColor=_j;_k.from=_k.setColor=_k.setHex=function(_l){var _m=this;if(_l instanceof _j){_m.encoding=_l.encoding;_n(_l.tuple,_m.tuple);}else{var _o;if(arguments.length==3){_o='RGB array';_l=_p(arguments);}else{if(_l==_a||typeof _l=='number'){_o='RGB int';}else if(typeof _l=='string'){if(_g[_l]!=_a||_g[_l.toLowerCase()]!=_a){_o='name';}else{var _q=_l.match(_c);_o=_q?_q[1].toUpperCase()+' string':_l.charCodeAt(0)==35?'#hex':'hex';}}else if(typeof _l=='object'){if(_l.length){_o='RGB array';}else if('red'in _l){_o='RGB object';}else if('lightness'in _l){_o='HSL object';}else{for(_o in _l)break;_l=_l[_o];}}}var _r=_s[_o];if(!_r){_r=_s[_o='RGB int'];_l=0;}
_r.from(_l,_m.tuple);_m.encoding=_o;}return _m;};_k.getTuple=function(_t){var _u=_v[_s[this.encoding].colorSpace],_w=_t?_v[_t]||_v[_s[_t].colorSpace]:_u;return(_w!=_u?_w.fromHsl(_u.toHsl(this.tuple)):this.tuple);};_k.setEncoding=function(_x){_n(this.getTuple(_x&&_x!='color'?_x:(_x='hex')),this.tuple);this.encoding=_x;return this;};_k.to=function(_x){return(_x=='color'?new _j(this):_s[_x||this.encoding].to(this.getTuple(_x)));};_k.toHex=function(){return this.to('hex')};_j.defineColors=function(_y){Uize.copyInto(_g,_y);_b&&_f(_y);};_j.hexStrToRgb=function(_l){return _j.to(_l,'RGB object')};_j.rgbToHexStr=function(_l){return _j.to(arguments.length==3?arguments:_l)};_j.rgbToStyleStr=function(_l){return _j.to(_l,'RGB string')};_j.from=_j.rgbFromStyleStr=function(){return _k.from.apply(new _j,arguments)};var _p=_j.cloneTuple=function(_z){var _A=_z[3];return(isNaN(_A)||_A==_a?[_z[0],_z[1],_z[2]]:[_z[0],_z[1],_z[2],_A]);};var _B=_j.setTuple=function(_z,_C,_D,_E,_A){_z[0]= +_C;_z[1]= +_D;_z[2]= +_E;_z[3]= +_A;};
var _n=_j.setTupleFromArray=function(_F,_z){_B(_z,_F[0],_F[1],_F[2],_F[3]);};var _G=_j.setTupleFromString=function(_H,_z){var _q=_H.match(_c);_B(_z,parseFloat(_q[2]),parseFloat(_q[3]),parseFloat(_q[4]),parseFloat(_q[5]));};_j.to=function(_I,_o){return _J.from(_I).to(_o||'hex')};var _v=_j.colorSpaces={sRGB:{fromHsl:function(_z){var _K=_z[1]/100,_L=_z[2]/100;if(_K){var _M=_L<.5?_L*(1+_K):_L+_K-_L*_K,_N=2*_L-_M;var _O=_z[0]/360;function _P(_Q){return((_Q=(_Q+1)%1)<1/6?_N+(_M-_N)*6*_Q:_Q<.5?_M:_Q<2/3?_N+(_M-_N)*6*(2/3-_Q):_N)*255;}return[_P(_O+1/3),_P(_O),_P(_O-1/3)];}else{var _R=_L*255;return[_R,_R,_R];}},toHsl:function(_z){var _S=_z[0]/255,_T=_z[1]/255,_U=_z[2]/255,_V=Math.max(_S,_T,_U),_W=Math.min(_S,_T,_U),_X=_V+_W,_Y=_V-_W,_O=0,_K=0,_L=_X/2;if(_Y){_K=_Y/(_L<.5?_X:2-_X);_O=((_S==_V?6+(_T-_U)/_Y:_T==_V?2+(_U-_S)/_Y:4+(_S-_T)/_Y)*60)%360;}function _Z(_Q){return Uize.constrain(_Q*100,0,100)}return[_O,_Z(_K),_Z(_L)];},tuple:[{name:'red',min:0,max:255},{name:'green',min:0,max:255},{name:'green',min:0,max:255}]},
HSL:{fromHsl:Object,toHsl:Object,tuple:[{name:'hue',min:0,max:360},{name:'saturation',min:0,max:100},{name:'lightness',min:0,max:100}]}};function _0(_l,_z){if(_l.charCodeAt(0)==35)_l=_l.slice(1);var _1=_l.length;_l='0x'+_l-0;_1==1?_B(_z,_l*=17,_l,_l):_1==3?_B(_z,((_l>>8)&15)*17,((_l>>4)&15)*17,(_l&15)*17):_B(_z,(_l>>16)&255,(_l>>8)&255,_l&255);}var _s=_j.encodings={hex:{colorSpace:'sRGB',from:_0,to:function(_z){return(0x1000000+_s['RGB int'].to(_z)).toString(16).slice(1);}},'#hex':{colorSpace:'sRGB',from:_0,to:function(_z){return'#'+_s['hex'].to(_z)}},name:{colorSpace:'sRGB',from:function(_i,_z){_s['RGB int'].from(_i in _g?_g[_i]:_g[_i.toLowerCase()],_z);},to:function(_z){if(!_b){_b={};_f(_g);}return _b[_s['RGB int'].to(_z)]||_s['hex'].to(_z);}},'RGB array':{colorSpace:'sRGB',from:_n,to:_p},'RGB int':{colorSpace:'sRGB',from:function(_2,_z){_2=Uize.constrain(Math.round(_2),0,16777215);_B(_z,(_2>>16)&255,(_2>>8)&255,_2&255);},to:function(_z){return(_d(_z[0])<<16)+(_d(_z[1])<<8)+_d(_z[2]);}},'RGB object':{
colorSpace:'sRGB',from:function(_3,_z){_B(_z,_3.red,_3.green,_3.blue);},to:function(_z){return{red:_z[0],green:_z[1],blue:_z[2]}}},'RGB string':{colorSpace:'sRGB',from:_G,to:function(_z){return'rgb('+_d(_z[0])+','+_d(_z[1])+','+_d(_z[2])+')';}},'HSL array':{colorSpace:'HSL',from:_n,to:_p},'HSL object':{colorSpace:'HSL',from:function(_4,_z){_B(_z,_4.hue,_4.saturation,_4.lightness);},to:function(_z){return{hue:_z[0],saturation:_z[1],lightness:_z[2]}}},'HSL string':{colorSpace:'HSL',from:_G,to:function(_z){function _5(_6){return Uize.constrain(Math.round(_6),0,100)+'%'}return('hsl('+Math.round(_z[0])+','+_5(_z[1])+','+_5(_z[2])+')');}}};var _g=_j.colors={white:16777215,silver:12632256,gray:8421504,black:0,navy:128,blue:255,aqua:65535,teal:32896,green:32768,olive:8421376,lime:65280,maroon:8388608,red:16711680,orange:16753920,yellow:16776960,purple:8388736,fuchsia:16711935};var _J=new _j,_7=new _j;return _j;}});