/*______________
|       ______  |   U I Z E    J A V A S C R I P T    F R A M E W O R K
|     /      /  |   ---------------------------------------------------
|    /    O /   |    MODULE : UizeDotCom.SiteMap
|   /    / /    |
|  /    / /  /| |    ONLINE : http://www.uize.com
| /____/ /__/_| | COPYRIGHT : (c)2009-2010 UIZE
|          /___ |   LICENSE : Available under MIT License or GNU General Public License
|_______________|             http://www.uize.com/license.html
*/
Uize.module({name:'UizeDotCom.SiteMap',required:'UizeDotCom.ModulesTree',builder:function(){var _a;return function(){if(!_a){var _b={title:'-'};function _c(_d){return'reference/'+_d+'.html';}function _e(_f,_g,_h){var _d=_f+(_f&&'.')+_g,_i=_c(_d),_j={title:_g,link:_i},_k=_j.items=[];if(_h)for(var _l in _h)_k.push(_e(_d,_l,_h[_l]));_k.length&&_d&&_k.unshift({title:'[[ BASE ]]',link:_i},_b);return _j;}var _m=_e('','',UizeDotCom.ModulesTree());_m.title='Module Reference';_m.link='javascript-modules-index.html';function _j(_n,_o,_p){
return{title:_n,link:(_o||'')+(_p||_n.toLowerCase().replace(/\W/g,'-'))+'.html'}}function _q(_n,_p){return _j(_n,'examples/',_p)}function _r(_n,_p){return _j(_n,'explainers/',_p)}function _s(_n,_p){return _j(_n,'appendixes/',_p)}function _t(_n,_p){return _j(_n,'tests/performance/',_p)}function _u(_v){var _w='javascript-'+(_v!='all'?(_v+'-'):'')+'examples.html';return{title:Uize.capFirstChar(_v)+' examples',link:_w,items:[{title:'TOUR '+_v.toUpperCase()+' EXAMPLES',link:'javascript-feature-tours.html?tour='+_v},_b,{title:'Index of '+_v+' examples',link:_w}]}}_a=[_j('Home','','index'),_j('DOWNLOAD'),_r('Getting Started'),_j('Latest News'),_b,{title:'Examples',link:'javascript-examples.html',items:[_u('featured'),_b,_u('animation'),_u('color'),_u('drag-and-drop'),_u('form'),_u('menu'),_u('slideshow'),_u('tool'),_u('widget'),_u('zoom'),_b,_u('all'),_b,{title:'EXAMPLES, BY MODULE...',link:'javascript-examples.html',items:[{title:'Uize.Color',items:[_q('Sortable Color Table'),_q('Color Sort by RGB Proximity'),
_q('Color Gradient Tool')]},{title:'Uize.Curve',items:[_q('Curve Explorer')]},{title:'Uize.Data',items:[_q('Simple Data Tester')]},{title:'Uize.Doc.Simple',items:[_q('SimpleDoc Tester','simple-doc-tester')]},{title:'Uize.Json',items:[_q('JSON Prettifier')]},{title:'Uize.Fade',items:[_q('Fade As a Graph'),_q('Fade As a Color Chart'),_q('Fade Quantization Chart'),_q('Fading an Object')]},{title:'Uize.Fx',items:[_q('Fade CSS Style Across Nodes')]},{title:'Uize.Scruncher',items:[_q('JavaScript Scruncher')]},{title:'Uize.Template',items:[_q('JavaScript Template Tester')]},{title:'Uize.Templates',items:[_q('List Template','templates-list')]},{title:'Uize.Widget',items:[{title:'AutoTooltip',items:[_q('Auto Tooltip for Photo Info','auto-tooltip-photo-info'),_q('Generic Auto Tooltip','auto-tooltip-generic')]},{title:'Bar',items:[_q('Bars For Data Comparison','bars'),_q('Basic Progress Bar','progress-bar'),{title:'Slider',items:[_q('Basic Slider','slider'),_q('Multiple Sliders from a Template','sliders-from-template'),
_q('The Built-in Slider Skin','slider-built-in-skin'),_q('Slider Plus Buttons','slider-plus'),_q('Sliders as RGB Selectors'),_q('Sliders in a Color Blender','sliders-in-color-blender'),_q('Characters Used Indicator','slider-chars-used')]}]},{title:'Bevel',items:[_q('Basic Bevel','bevel'),_q('Bevel On Multiple Images')]},{title:'Button',items:[_q('Button Types'),_q('Uize.Widget.Button.Toggle','button-toggle')]},_q('Calculator','javascript-calculator-widget'),{title:'Calendar',items:[_q('Calendar Controls Wikipedia'),_q('Calendar')]},{title:'Collection.Dynamic',items:[_q('Dynamic Collection','collection-dynamic')]},{title:'CollectionItem.Zooming',items:[_q('Zooming Collection Items','collection-item-zooming'),_q('Coupled Zooming Collection Items','collection-item-coupled-zooming')]},{title:'ColorCube',items:[_q('Basic Color Cube','color-cube'),_q('Color Cube With Color Pickers','color-cube-with-pickers')]},{title:'ColorPicker',items:[_q('Color Picker'),_q('Color Pickers With Gradient')]},{title:'Dialog',items:[
_q('Dialog'),_q('Resizable Dialog','dialog-resizable')]},{title:'Drag',items:[{title:'Move',items:[_q('Drag-to-move')]}]},{title:'HoverFader',items:[_q('Fading Links'),_q('Hover Fader Color Effects'),_q('Hover Fader Stretching Menu'),_q('Hover Fader for Thumbnails'),_q('Hover Fader Text Shadow Animation')]},{title:'ImagePort',items:[_q('Basic Image Port','image-port'),_q('Image Port Inside a Marquee','image-port-with-marquee'),_q('Draggable Image Port','image-port-drag'),_q('Zoom and Pan','image-port-zoom-and-pan'),_q('Tiled Zoom and Pan','image-port-zoom-and-pan-tiled')]},_q('ImageWipe','image-wipe'),{title:'ListEditor',items:[_q('Domain List Editor')]},_q('MagView','mag-view'),_q('Mask'),{title:'Options',items:[_q('Options'),_q('Dynamic Options','options-dynamic'),{title:'Options.Tabbed',items:[_q('Tabbed Interface'),_q('Tabbed Interface With Fade')]}]},_q('Picker.Date','date-picker'),{title:'Population',items:[_q('Structured Record Population','population-structured-record'),_q('Populating Photo Details')]
},{title:'Resizer.Marquee',items:[_q('Basic Marquee','marquee'),_q('Different Marquee Modes','marquee-modes'),_q('Marquee and Image Port'),_q('Marquee With Rest Update')]},{title:'Scrolly',items:[_q('Scrolly'),_q('Scrolly Carousel')]},{title:'SlideShow',items:[_q('Slideshow'),_q('Slideshow With Dissolve'),_q('Slideshow With Wipes'),_q('Slideshow of Data')]},{title:'Swap',items:[_q('Image Swap','swap-image'),_q('Deck Swapper','swap-deck'),_q('Cycling Image Swap','swap-image-cycle'),_q('Basic HTML Swap','swap-html'),_q('Image Swap With PNGs','swap-image-png')]},{title:'TableSort',items:[_q('Basic Table Sort','table-sort-basic'),_q('Complex Table Sort','table-sort-complex')]},_q('ThumbZoom'),{title:'Tree',items:[_q('Tree List From JSON','tree-list'),_q('Tree Menu From JSON','tree-menu'),_q('Hierarchical Selector'),_q('Two Hierarchical Selectors')]},{title:'Widget Functionality',items:[_q('enabled/busy in Widget Tree'),_q('Decorated Confirm Dialog','decorated-confirm'),_q('Shared UI'),_q('Transferring State'),
_q('The setNodeValue Method','set-node-value'),_q('setNodeValue on Multi-select','set-node-value-multi-select'),_q('Virtual DOM Events'),_q('Edge Virtual DOM Events')]}]},{title:'Sequenced Show Examples',items:[_q('Sequenced Show'),_q('Sequenced Show Using Swap')]}]}]},{title:'Explainers',link:'javascript-explainers.html',items:[_r('Introduction to UIZE'),_r('Getting Started With UIZE','getting-started'),_r('Using the Documentation'),_r('Overview of Features'),_r('Building UIZE-powered Pages'),{title:'MORE TOPICS...',items:[_r('JavaScript Animation and Effects'),_r('JavaScript Inheritance'),_r('Set-get Properties'),_r('JavaScript Event System'),_r('JavaScript DOM Events'),_r('JavaScript Localization'),_r('JavaScript Modules'),_r('JavaScript Libraries'),_r('JavaScript Templates'),_r('JavaScript Widgets'),_r('JavaScript Troubleshooting'),_r('JavaScript Build Scripts'),_r('All About Scrunching'),_r('JavaScript Documentation System'),_r('The Philosophy of UIZE','philosophy-of-uize')]},_b,{
title:'For Framework Developers',items:[_s('SOTU (State of the UIZE)','sotu')]},_b,_j('Index of JavaScript Explainers','','javascript-explainers')]},_m,{title:'Tools',link:'javascript-tool-examples.html',items:[_q('Curve Explorer'),_q('Color Gradient Tool'),_q('JSON Prettifier'),_q('JavaScript Template Tester'),_q('JavaScript Scruncher'),_q('SimpleDoc Tester','simple-doc-tester'),_q('Simple Data Tester'),_b,_j('Index of JavaScript Tools','','javascript-tool-examples')]},{title:'Tests',items:[{title:'Performance Tests',items:[_t('Array Iteration Styles'),_t('Caching Node References'),_t('Checking if Undefined'),_t('Extended String Class'),_t('getElementById vs getElementsByName','getElementById-vs-getElementsByName'),_t('Repeat String Approaches'),_t('Storing Length for Iterator'),_t('Storing Reference to Sub-object','storing-reference-to-subobject'),_t('String Concatenation Approaches'),_t('String Match Conditional Styles'),_t('String Starts With Substring Styles')]}]},{title:'Appendixes',items:[
_s('Code Fragments'),_s('Credits'),_j('Endorsements'),_j('Index of JavaScript Modules','','javascript-modules-index'),_s('Glossary'),_s('HTML Style Guide'),_s('JavaScript Code Conventions'),_s('JavaScript Fun'),_s('JavaScript Interview Questions'),_s('JavaScript Optimization'),_s('SOTU (State of the UIZE)','sotu'),_j('License'),_s('Press Center')]},_b,_j('SUPPORT'),_j('SITE MAP','','directory'),_j('SEARCH','','search-sections')];}return _a;};}});