/*
	UIZE JAVASCRIPT FRAMEWORK 2010-01-24

	http://www.uize.com/reference/Uize.Test.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Test',required:['Uize.Data','Uize.Json'],builder:function(b_a){var b_b=true,b_c=false,b_d;var b_e=b_a.subclass(),b_f=b_e.prototype;b_f.b_g=function(b_h,b_i,b_j){b_h||this.set({b_k:'EXPECTED:\n\n'+b_i()+'\n\n'+'ACTUAL:\n\n'+b_j()});return b_h;};b_f.expect=function(b_l,b_m){return this.b_g(Uize.Data.identical(b_l,b_m),function(){return Uize.Json.to(b_l)},function(){return Uize.Json.to(b_m)});};b_f.expectInstanceOf=function(b_e,b_m){return this.b_g(typeof b_m=='object'&&b_m&&b_m.constructor==(typeof b_e=='string'?eval(b_e):b_e).prototype.constructor,function(){return'instance of '+b_e},function(){return b_m.constructor});};b_f.expectType=function(b_n,b_m){return this.b_g(typeof b_m==b_n,function(){return'type '+b_n},function(){return'type '+typeof b_m});};b_f.expectArray=function(b_m){return this.expectInstanceOf(Array,b_m);};b_f.expectBoolean=function(b_m){return this.expectType('boolean',b_m);};b_f.expectFunction=function(b_m){return this.expectType('function',b_m);};
b_f.expectNumber=function(b_m){return this.expectType('number',b_m);};b_f.expectObject=function(b_m){return this.expectType('object',b_m);};b_f.expectRegExp=function(b_m){return this.expectInstanceOf(RegExp,b_m);};b_f.expectString=function(b_m){return this.expectType('string',b_m);};b_f.expectArrayLike=function(b_m){return this.b_g(Uize.isArray(b_m),function(){return'array like'},function(){return Uize.Json.to(b_m)});};b_f.expectValueRange=function(b_o,b_p,b_m){return this.b_g(b_m>=b_o&&b_m<=b_p,function(){return'value within range '+b_o+' to '+b_p},function(){return Uize.Json.to(b_m)});};b_f.expectNegativeValue=function(b_m){return this.expectValueRange(-Infinity,0,b_m);};b_f.expectPositiveValue=function(b_m){return this.expectValueRange(0,Infinity,b_m);};b_f.expectLengthRange=function(b_q,b_r,b_m){var b_s=b_m.length;return this.b_g(b_s>=b_q&&b_s<=b_r,function(){return'length within range '+b_q+' to '+b_r},function(){return b_s});};b_f.expectNonEmpty=function(b_m){return this.b_g(!Uize.Data.isEmpty(b_m),
function(){return'non-empty'},function(){return Uize.Json.to(b_m)});};b_f.expectInteger=function(b_m){return this.b_g(Math.floor(b_m)== +b_m,function(){return'integer'},function(){return Uize.Json.to(b_m)});};b_f.expectNegativeInteger=function(b_m){return this.expectInteger(b_m)&&this.expectNegativeValue(b_m);};b_f.expectPositiveInteger=function(b_m){return this.expectInteger(b_m)&&this.expectPositiveValue(b_m);};b_f.expectNoRepeats=function(b_t){return Uize.Data.getTotalKeys(Uize.Data.getLookup(b_t))==b_t.length;};b_f.expectNonEmptyArray=function(b_m){return this.expectArray(b_m)&&this.expectNonEmpty(b_m);};b_f.expectNonEmptyObject=function(b_m){return this.expectObject(b_m)&&this.expectNonEmpty(b_m);};b_f.expectNonEmptyString=function(b_m){return this.expectString(b_m)&&this.expectNonEmpty(b_m);};b_f.run=function(b_u){var b_v=this,b_w=b_v.b_w,b_x=b_b;b_v.set({b_y:new Date,b_z:b_d,b_A:b_c,b_B:[],b_C:b_d,b_k:b_d});b_v.fire('Start');function b_D(){b_v.set({b_C:b_x});if(b_x==b_A){b_v.set({b_A:b_b});}else{
var b_z=new Date;b_v.set({b_E:b_z-b_v.b_y,b_z:b_z});!b_x&&b_v.b_F!=null&&alert('TEST FAILED: '+b_v.b_F+'\n'+((b_v.b_k||'')&&('\n'+'REASON FOR FAILURE:\n'+'\n'+b_v.b_k)));b_v.fire('Done');b_v.b_A&&b_u&&b_u(b_x);}}if(Uize.isArray(b_w)){var b_G=b_w.length,b_H= -1,b_I;function b_J(){function b_K(b_C){b_x=b_C;b_J();}while(b_x&& ++b_H<b_G&&(b_x=(b_I=new b_w[b_H]).run(b_K))!=b_A);b_D();}b_J();}else{try{b_x=b_A;var b_L=b_c,b_M=b_w.call(b_v,function(b_C){b_x=b_C;b_L&&b_D();});if(b_M!==b_d)b_x=b_M;b_L=true;}catch(b_N){b_v.set({b_k:'JavaScript Error...\n'+'ERROR NAME: '+b_N.name+'\n'+'ERROR MESSAGE: '+b_N.message+'\n'+'ERROR DESCRIPTION: '+b_N.description+'\n'+'LINE NUMBER: '+b_N.number+'\n'});b_x=b_c;}b_D();}return b_x;};var b_A=b_e.isAsync={};b_e.addTest=function(b_w){(this.b_w||(this.b_w=[])).push(b_w);};b_e.declare=function(b_w){var b_O=b_e.subclass();var b_P=b_w.test;if(Uize.isArray(b_P)){for(var b_Q= -1,b_R=b_P.length;++b_Q<b_R;){var b_S=b_P[b_Q];if(b_S.constructor==Object)b_P[b_Q]=b_e.declare(b_S);}}b_O.set(b_w);
return b_O;};b_e.log=function(b_T){this.b_B.push({timestamp:new Date,message:b_T});};b_e.requiredModulesTest=function(b_U){return Uize.Test.declare({title:'REQUIRED MODULES TEST: '+b_U,test:function(b_J){Uize.module({required:b_U,builder:function(){b_J(true)}});}});};b_e.staticMethodTest=function(b_V,b_W,b_X){var b_Y=b_V.lastIndexOf('.'),b_Z=b_V.slice(0,b_Y),b_0=b_V.slice(b_Y+1),b_w=[{title:'Test that host '+b_Z+' is defined',test:function(){var b_h= !!eval(b_Z);b_h||this.set({b_k:'The host for static method '+b_V+', '+b_Z+', is not defined'});return b_h;}},{title:'Test that static method '+b_V+' is defined',test:function(){var b_h= !!eval(b_Z)[b_0];b_h||this.set({b_k:'Static method '+b_V+' is not defined'});return b_h;}},{title:'Test that '+b_V+' is a function',test:function(){var b_1=typeof eval(b_Z)[b_0],b_h=b_1=='function';b_h||this.set({b_k:b_V+' should be a function, but is of type '+b_1});return b_h;}}];function b_2(b_3){return(Uize.isArray(b_3)?b_e.declare({title:b_3[0],test:function(){var
 b_4=eval(b_Z),b_5=b_3[1];return this.expect(b_3[2],b_4[b_0].apply(b_4,Uize.isArray(b_5)?b_5:[b_5]));}}):b_3);}for(var b_6= -1,b_7=b_W.length;++b_6<b_7;)b_w.push(b_2(b_W[b_6]));return b_e.declare(b_e.copyInto({title:'STATIC METHOD TEST: '+b_V,test:b_w},b_X));};b_e.staticMethodTests=function(b_8){var b_w=[];for(var b_9= -1,b_ba=b_8.length;++b_9<b_ba;){var b_bb=b_8[b_9];b_w.push(Uize.isArray(b_bb)?b_e.staticMethodTest.apply(this,b_bb):b_bb);}return b_e.declare({title:'Static Method Tests',test:b_w});};b_e.registerProperties({b_A:'isAsync',b_E:'duration',b_z:'endTime',b_B:'log',b_bc:'reasongForFailure',b_C:'result',b_w:'test',b_y:'startTime',b_F:'title'});return b_e;}});