/*
	UIZE JAVASCRIPT FRAMEWORK 2010-01-24

	http://www.uize.com/reference/Uize.Widget.Drag.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Widget.Drag',required:['Uize.Node','Uize.Node.Event','Uize.Fade'],builder:function(c_a){var c_b,c_c=true,c_d=false,c_e=null,c_f=Uize.Node,c_g=c_f.isIe,c_h=((!c_g||navigator.appVersion.indexOf('MSIE 6')== -1)&&navigator.userAgent.indexOf('Firefox/2')<0);var c_i;var c_j=c_a.subclass(function(){var c_k=this;c_k.eventStartPos=c_k.c_l=[0,0];c_k.eventPos=c_k.c_m=[0,0];c_k.eventDeltaPos=c_k.c_n=[0,0];}),c_o=c_j.prototype;c_o.c_p=function(){this.c_q=null;this.fire('Drag Rest');};c_o.c_r=function(){this.c_q&&clearTimeout(this.c_q);this.c_q=null;};c_o.c_s=function(){var c_k=this;if(c_k.isWired){var c_t=c_k.getNode();c_k.c_u?c_f.setStyle(c_k.c_v?[c_t,c_i]:c_t,{cursor:c_k.get('enabledInherited')?c_k.c_u:'not-allowed'}):c_k.set({c_u:c_f.getStyle(c_t,'cursor')});}};c_o.mousedown=function(c_w){var c_k=this;if(!c_k.c_v&&c_k.get('enabledInherited')){c_k.set({c_v:c_c});c_k.c_s();Uize.Node.Event.abort(c_w);c_k.c_x=c_w.shiftKey?'one':'both';c_k.fire({name:'Before Drag Start',domEvent:c_w});
c_k.c_l[0]=c_w.clientX;c_k.c_l[1]=c_w.clientY;var c_y=c_d,c_z=document.onkeyup,c_A=document.onmousemove,c_B=document.onmouseup;function c_C(c_w){if(c_k.c_v){c_y=c_c;if(c_k.c_q){c_k.c_r();c_k.c_p();}c_k.set({c_v:c_d});c_k.fire({name:'Drag Done',domEvent:c_w});c_k.set({c_D:c_d,c_E:c_d});}}function c_F(c_w){c_C(c_w);document.onmousemove=c_A;document.onmouseup=c_B;document.onkeyup=c_z;c_f.display(c_i,c_d);}function c_G(c_H,c_I){c_k.c_m[0]=c_H;c_k.c_m[1]=c_I;var c_n=[c_k.c_m[0]-c_k.c_l[0],c_k.c_m[1]-c_k.c_l[1]],c_J=[Math.abs(c_n[0]),Math.abs(c_n[1])];function c_K(c_L){return((c_k.c_x=='both'||c_J[c_L]>c_J[1-c_L]||(c_J[c_L]==c_J[1-c_L]&&c_L==1))?c_n[c_L]:0);}c_k.c_n[0]=c_K(0);c_k.c_n[1]=c_K(1);c_k.fire('Drag Update');c_k.c_r();c_k.c_q=setTimeout(function(){c_k.c_p()},c_k.c_M);}document.onmousemove=function(c_w){if(!c_w)c_w=event;if(c_g&&c_w.button==0){c_k.c_v&&c_F(c_w);}else{if(!c_y){if(!c_k.c_E){c_j.resizeShield(c_i);c_f.display(c_i);c_k.set({c_E:c_c});c_k.fire({name:'Drag Start',domEvent:c_w});}
c_G(c_w.clientX,c_w.clientY);}}return c_d;};document.onmouseup=function(c_w){if(!c_w)c_w=event;c_F(c_w);return c_d;};document.onkeyup=function(c_w){if(Uize.Node.Event.isKeyEscape(c_w)&&c_k.c_v){c_k.set({c_D:c_c});if(c_k.c_N){var c_O=c_k.fade,c_P={'Changed.value':function(){var c_Q=c_O.valueOf();c_G(c_Q[0],c_Q[1]);},Done:function(){c_O.unwire(c_P);c_C(c_w);}};c_O.wire(c_P);c_O.start({startValue:c_k.c_m,endValue:c_k.c_l});}else{c_G(c_k.c_l[0],c_k.c_l[1]);c_C(c_w);}}};}return c_d;};c_o.updateUi=function(){var c_k=this;c_k.isWired&& !c_k.get('enabledInherited')||c_k.c_u&&c_k.c_s();};c_o.wireUi=function(){var c_k=this;if(!c_k.isWired){var c_R=c_k.getNode();if(c_R){c_R.onmousedown=c_f.returnFalse;c_k.wireNode(c_R,'mousedown',function(c_w){return c_k.mousedown(c_w)});}if(!c_i)c_i=c_j.insertShield({zIndex:50000});c_k.wire({'Changed.enabledInherited':function(){c_k.c_s()}});c_a.prototype.wireUi.call(c_k);}};c_j.insertShield=function(c_S){var c_T={display:'none',position:'absolute'};if(c_g)
c_T.background='url('+c_j.getBlankImageUrl()+')';var c_U=document.createElement('div');c_f.setStyle(c_U,c_j.copyInto(c_T,c_S));c_U.Uize_Widget_Drag_shield=c_c;document.body.appendChild(c_U);c_j.resizeShield(c_U);return c_U;};c_j.resizeShield=function(c_U){if(c_h){c_f.setStyle(c_U,{left:'0',top:'0',width:'100%',height:'100%',position:'fixed'});}else{var c_V=c_f.getStyle(c_U,'display'),c_W=document.documentElement,c_X=document.body;c_f.display(c_U,c_d);c_f.setStyle(c_U,{left:0,top:0,width:c_W.scrollWidth,height:Math.max(typeof window.innerHeight=='number'?window.innerHeight:(c_W&&c_W.clientHeight?c_W.clientHeight:(c_X&&c_X.clientHeight?c_X.clientHeight:0)),c_W.scrollHeight),display:c_V});}};c_j.registerProperties({c_N:{name:'animation',onChange:function(){if(this.c_N&& !this.fade)this.fade=new Uize.Fade({duration:500});},value:c_d},c_u:{name:'cursor',onChange:c_o.c_s},c_D:{name:'dragCancelled',value:c_d},c_M:{name:'dragRestTime',value:250},c_E:{name:'dragStarted',value:c_d},c_v:{name:'inDrag',value:c_d}});
!c_h&&c_a.wire('Window Resized',function(){c_j.resizeShield(c_i)});return c_j;}});