/*
	UIZE JAVASCRIPT FRAMEWORK 2010-01-24

	http://www.uize.com/reference/Uize.Widget.Button.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Widget.Button',required:'Uize.Node',builder:function(c_a){var c_b,c_c=true,c_d=false,c_e=Uize.Node;var c_f=c_a.subclass(),c_g=c_f.prototype;var c_h,c_i={},c_j={grayed:16,'':8,over:4,active:2,playing:1},c_k='(Grayed|Over|Active|Playing)',c_l=new RegExp(c_k),c_m=new RegExp('(?:(?:(\\S+)\\s+\\1'+c_k+'))','g'),c_n=new RegExp('\\S*'+c_k+'\\b','g'),c_o=/\b(disabled|over|active|playing)\b/,c_p={},c_q={mouseover:['over','Over'],mouseout:['','Out'],mousedown:['down','Down'],mouseup:['over','Up'],click:['over','Click']};c_g.c_r=c_d;c_g.c_s=function(){return(this.get('enabledInherited')&& !this.get('busyInherited')&&(!this.c_t||this.c_u));};c_g.c_v=function(){this.c_w!=c_b&&this.isWired&&this.setNodeInnerHtml('text',this.c_w);};var c_x=c_g.c_x=function(){var c_y=this;if(c_y.isWired){var c_z=c_y.c_z,c_A=c_y.get('enabledInherited'),c_B=c_y.get('busyInherited'),c_C=(!c_A?16:0)|(!c_y.c_D||c_B?8:0)|(c_y==c_h?4:0)|(c_y.c_D=='down'||c_y.c_t?2:0)|(c_y.c_E?1:0),c_F=c_y.c_G[c_C];if(c_F==c_b){for(var
 c_H= -1,c_I=c_y.c_I,c_J=c_I.length;++c_H<c_J;){var c_K=c_I[c_H];if(c_C&c_j[c_K]){c_F=c_K;break;}}c_y.c_G[c_C]=c_F;}if(c_y.c_L=='classes'){var c_M=c_z.className,c_N='';if(c_y.c_O=='disambiguated'){var c_P=c_y.c_P;if(c_P==c_b){var c_Q=c_M.match(c_m);if(c_Q){c_P=c_Q[c_Q.length-1].split(' ',2)[0];}else{c_Q=c_M.replace(c_n,'').match(/(\S+)\s*$/);if(c_Q)c_P=c_Q[c_Q.length-1];}if(c_y.c_P=c_P=c_P||'')c_y.c_R=c_p[c_P]||(c_p[c_P]=new RegExp(c_P+'(\\s+'+c_P+c_k+')?'));}var c_S=c_F?' '+c_P+c_f.capFirstChar(c_F):'';c_N=c_P?c_M.replace(c_y.c_R,c_P+c_S):c_M.replace(c_l,'')+c_S;}else{var c_T=c_F=='grayed'?'disabled':c_F;c_N=c_o.test(c_M)?c_M.replace(c_o,c_T):c_M+(c_T?' ':'')+c_T;}if(c_N!=c_M)c_z.className=c_N;}else if(c_y.c_L=='frames'){c_y.c_U.style.top='-'+(c_y.c_V.c_W[c_F]*c_y.c_X.height)+'px';}if(c_y.c_Y&&Uize.Tooltip){var c_Z=c_y.c_D=='over'&&c_A&& !c_y.c_t;c_Z!=c_y.c_r&&Uize.Tooltip.showTooltip(c_y.c_Y,c_y.c_r=c_Z);}c_y.get('busyInherited')?c_e.setStyle(c_z,{cursor:'wait'}):c_e.showClickable(c_z,c_y.c_s());}};
c_g.c_0=function(c_1){var c_y=this;if(c_y.isWired){var c_2=c_1.type,c_3=c_2=='click',c_s=c_y.c_s();if(!c_y.c_4){c_y.c_4=c_c;function c_0(c_1){c_y.c_0(c_1)}c_y.wireNode(c_y.c_z,{mouseout:c_0,mousedown:c_0,mouseup:c_0});}if(c_3)c_1.cancelBubble=c_c;if(c_s){var c_5=c_q[c_2];c_y.set({c_D:c_5[0]});c_y.fire({name:c_5[1],domEvent:c_1});}}};c_g.updateUi=function(){this.c_x();this.c_v();};c_g.wireUi=function(){var c_y=this;if(!c_y.isWired){c_y.c_U=c_b;var c_z=c_y.c_z=c_y.getNode();if(c_z){var c_6=c_z.childNodes;if(c_6.length&&(c_6.length>1||c_6[0].nodeType!=3)&&(c_y.c_U=c_y.getNode('frames'))){c_y.c_L='frames';c_y.c_X=c_e.getDimensions(c_y.c_U.parentNode);}if(c_y.c_7&&c_z.tagName=='A'&& !c_z.onclick)c_z.onclick=c_e.returnTrue;function c_0(c_1){c_y.c_0(c_1)}c_y.wireNode(c_z,{mouseover:c_0,click:c_0});function c_x(){c_y.c_x()}c_y.wire({'Changed.busyInherited':c_x,'Changed.enabledInherited':c_x});c_a.prototype.wireUi.call(c_y);}}};c_f.addChildButton=function(c_8,c_9){var c_y=this,c_ba;function c_bb(){c_ba.wire('Click',
function(c_bc){if(c_9)typeof c_9=='string'?c_y.fire(c_9):c_9(c_bc);c_y.fire(c_bc);});}if(c_y==c_f){c_ba=new c_f({idPrefix:c_8,name:c_8,c_7:c_c});c_bb();(window[c_ba.instanceId]=c_ba).wireUi();}else{c_ba=c_y.children[c_8];if(!c_ba){c_ba=c_y.addChild(c_8,c_f);c_bb();}}return c_ba;};c_f.registerProperties({c_u:{name:'clickToDeselect',onChange:c_x,value:c_d},c_O:{name:'classNamingForStates',value:'disambiguated'},c_V:{name:'frameOrder',onChange:function(){var c_V=this.c_V;if(!c_V.c_W){for(var c_bd= -1,c_be=c_V.length,c_W=c_V.c_W={};++c_bd<c_be;)c_W[c_V[c_bd]]=c_bd;}},value:['grayed','','over','active','playing']},c_7:{name:'followLink',value:c_d},c_L:{name:'mode',value:'classes'},c_E:{name:'playing',onChange:c_x,value:c_d},c_t:{name:'selected',onChange:c_x,value:c_d},c_D:{name:'state',onChange:function(){var c_y=this;if(!c_y.c_D){if(c_h==c_y)c_h=c_b;}else if(c_y.c_D=='over'){c_h&&c_h!=c_y&&c_h.set({c_D:''});c_h=c_y;}c_y.isWired&&c_y.c_x();},value:''},c_I:{name:'statePrecedence',onChange:function(){var c_y=this,
c_bf=c_y.c_I.c_bg||(c_y.c_I.c_bg=c_y.c_I.join(','));c_y.c_G=c_i[c_bf]||(c_i[c_bf]={});c_y.isWired&&c_y.c_x();},value:['playing','active','grayed','over','']},c_w:{name:'text',onChange:c_g.c_v},c_Y:'tooltip'});return c_f;}});