/*
	UIZE JAVASCRIPT FRAMEWORK 2010-01-24

	http://www.uize.com/reference/Uize.Widget.Resizer.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Widget.Resizer',required:['Uize.Node','Uize.Widget.Drag'],builder:function(c_a){var c_b=true,c_c=false,c_d=Uize.Node,c_e=Uize.Widget.Drag,c_f=c_d.isIe;var c_g=c_a.subclass(function(){this.c_h={};}),c_i=c_g.prototype;var c_j=navigator.appName=='Microsoft Internet Explorer'&&document.compatMode!='CSS1Compat',c_k={northWest:[0,0],north:[.5,0],northEast:[1,0],west:[0,.5],move:['both','both'],east:[1,.5],southWest:[0,1],south:[.5,1],southEast:[1,1]};c_i.c_l=function(c_m,c_n){var c_o=c_n[c_m];return c_o!=.5&&(c_o=='both'|| !(c_m?this.c_p:this.c_q));};c_i.c_r=function(){var c_s=this;if(c_s.isWired){for(var c_t in c_k){var c_n=c_k[c_t];c_s.children[c_t].set({enabled:c_s.c_l(0,c_n)||c_s.c_l(1,c_n)?'inherit':c_c});}}};c_i.c_u=function(){var c_s=this;if(c_s.isWired&& !(c_s.c_v=c_s.c_w)){var c_x=c_d.getDimensions(c_s.getNode('shell'));if(c_x.width&&c_x.height)c_s.c_v=[0,0,c_x.width-1,c_x.height-1];}};c_i.c_y=function(){var c_s=this;c_s.c_u();var c_v=c_s.c_v;if(c_v){
c_s.c_z=[c_v[2]-c_v[0]+1,c_v[3]-c_v[1]+1];c_s.c_A();}};var c_A=c_i.c_A=function(){var c_s=this;if(c_s.isWired&&(!c_s.c_B||c_s.c_C)){c_s.c_u();if(c_s.c_v){var c_D=c_s.c_D,c_v=c_s.c_v,c_z=c_s.c_z,c_E=c_s.c_E,c_F=c_s.c_F,c_G=c_s.c_G,c_H=c_s.c_H,c_I,c_J,c_K=c_s.c_K;if(c_K!=null){c_I=c_G;c_J=c_H;}else{c_I=c_g.constrain(c_G,c_s.c_L,c_D?c_z[0]:Infinity);c_J=c_g.constrain(c_H,c_s.c_M,c_D?c_z[1]:Infinity);}var c_N=c_D?c_g.constrain(c_E,c_v[0],c_v[2]-c_I+1):c_E,c_O=c_D?c_g.constrain(c_F,c_v[1],c_v[3]-c_J+1):c_F;if(c_N!=c_E||c_O!=c_F||c_I!=c_G||c_J!=c_H)c_s.set({c_E:c_N,c_F:c_O,c_G:c_I,c_H:c_J});}}};c_i.setPositionDuringDrag=function(c_E,c_F,c_G,c_H){var c_s=this;if(c_E!=c_s.c_E||c_F!=c_s.c_F||c_G!=c_s.c_G||c_H!=c_s.c_H){c_s.set({left:c_E,top:c_F,width:c_G,height:c_H});c_s.fire('Position Changed');}};c_i.getCoords=function(){var c_s=this;return{left:c_s.c_E,top:c_s.c_F,width:c_s.c_G,height:c_s.c_H};};c_i.updateUi=function(){var c_s=this;if(c_s.isWired){function c_P(c_Q){function c_R(c_S){
return parseInt(c_d.getStyle(c_T,'border'+c_S+'Width'))||0;}var c_T=c_s.getNode(c_Q);if(c_T){var c_U=Math.max(c_s.c_G-(c_j?0:c_R('Left')+c_R('Right')),0);if(c_f)c_U==c_s.c_h[c_Q]?c_s.displayNode('jiggler',c_s.c_V= !c_s.c_V):(c_s.c_h[c_Q]=c_U);c_d.setStyle(c_T,{left:c_s.c_E,top:c_s.c_F,width:c_U,height:Math.max(c_s.c_H-(c_j?0:c_R('Top')+c_R('Bottom')),0)});}}for(var c_W= -1,c_X=c_s.c_X,c_Y=c_X.length;++c_W<c_Y;)c_P(c_X[c_W]);}};c_i.wireUi=function(){var c_s=this;if(!c_s.isWired){var c_v,c_Z,c_n,c_0;function c_1(c_t){c_n=c_k[c_t];var c_2=c_s.addChild(c_t,c_e,{cursor:c_t=='move'?c_t:c_t.charAt(0)+(c_t.match(/[A-Z]|$/))[0]+'-resize',dragRestTime:c_s.c_3,node:c_s.getNode(c_t),resizerInfo:{c_t:c_t,c_n:c_n}});c_2.wire({'Before Drag Start':function(c_4){c_s.fire(c_4)},'Drag Start':function(c_4){c_s.c_5=c_4.source;c_s.set({c_B:c_b});c_s.c_y();c_v=c_s.c_v;c_Z=[c_v[2]/2,c_v[3]/2];c_0=[c_s.c_E,c_s.c_F,c_s.c_E+c_s.c_G-1,c_s.c_F+c_s.c_H-1];c_s.fire(c_4);},'Drag Update':function(){var c_K=c_s.c_K,c_6=c_s.c_5.resizerInfo,
c_n=c_6.c_n,c_7=c_n.concat(),c_8=c_0.concat();function c_9(c_m){if(c_s.c_l(c_m,c_n)){var c_o=c_n[c_m],c_ba=c_2.eventDeltaPos[c_m];if(c_o=='both'){if(c_s.c_D)c_ba=c_g.constrain(c_ba,c_v[c_m]-c_8[c_m],c_v[c_m+2]-c_8[c_m+2]);c_8[c_m]+=c_ba;c_8[c_m+2]+=c_ba;}else{var c_bb=c_m+c_o*2;c_8[c_bb]+=c_ba;if(c_s.c_D)c_8[c_bb]=c_g.constrain(c_8[c_bb],c_v[c_m],c_v[c_m+2]);if(c_K==null&&c_8[c_m]>c_8[c_m+2]){var c_bc=c_8[c_m];c_8[c_m]=c_8[c_m+2];c_8[c_m+2]=c_bc;c_7[c_m]=1-c_7[c_m];}}}}c_9(0);c_9(1);var c_bd=[Math.max(c_8[2]-c_8[0]+1,c_s.c_L),Math.max(c_8[3]-c_8[1]+1,c_s.c_M)],c_be=[(c_8[0]+c_8[2])/2,(c_8[1]+c_8[3])/2];if(c_K!=null){if(c_bd[0]/c_bd[1]!=c_K){var c_bf=[c_bd[1]*c_K,c_bd[0]/c_K];function c_bg(c_m,c_bh){c_bd[c_m]=c_bf[c_m];if(c_s.c_D){c_bd[c_m]=Math.min(c_bd[c_m],c_bh);c_bd[1-c_m]=c_bd[c_m]*Math.pow(c_K,c_m*2-1);}}function c_bi(c_m){c_bg(c_m,(c_be[c_m]<c_Z[c_m]?(c_be[c_m]+.5):c_v[c_m+2]-c_be[c_m])*2);}function c_bj(c_m){c_bg(c_m,(c_n[c_m]?c_v[c_m+2]-c_8[c_m]:c_8[c_m+2])+1);}if(c_n[0]==.5){c_bi(0);
}else if(c_n[1]==.5){c_bi(1);}else if(c_bd[1]*c_bf[0]>c_bd[0]*c_bf[1]){c_bj(0);}else{c_bj(1);}}function c_bk(c_m){if(!c_n[c_m]){c_8[c_m]=c_8[c_m+2]-c_bd[c_m]+1;}else if(c_n[c_m]==.5){c_8[c_m]=c_be[c_m]-(c_bd[c_m]-1)/2;}}c_bk(0);c_bk(1);}c_s.set({activeHandleEffectivePointIdX:c_7[0],activeHandleEffectivePointIdY:c_7[1]});c_s.setPositionDuringDrag(c_8[0],c_8[1],c_bd[0],c_bd[1]);},'Drag Rest':function(c_4){c_s.fire(c_4)},'Drag Done':function(c_4){c_s.set({c_B:c_c});c_s.fire(c_4);c_s.set({c_C:c_c});c_s.updateUi();}});}for(var c_t in c_k)c_1(c_t);c_s.c_r();if(c_f){var c_Q=c_s.getNode(c_s.c_X[0]);if(c_Q){var c_bl=document.createElement('div');c_bl.id=c_s.get('idPrefix')+'-jiggler';c_d.setStyle(c_bl,{position:'absolute'});c_Q.appendChild(c_bl);}}c_a.prototype.wireUi.call(c_s);c_s.c_y();}};c_g.pointIdsMap=c_k;var c_bm='updateUi',c_bn=[c_bm,c_i.c_r],c_bo=[c_A,c_bm];c_g.registerProperties({c_bp:'activeHandleEffectivePointIdX',c_bq:'activeHandleEffectivePointIdY',c_X:{name:'areaNodes',value:['']},c_K:{
name:'aspectRatio',onChange:c_bm,value:null},c_D:{name:'constrain',value:c_b,onChange:c_A},c_w:{name:'constrainBounds',value:null,onChange:c_i.c_y},c_C:{name:'creatingNew',value:c_c},c_3:{name:'dragRestTime',onChange:function(){c_g.callOn(this.children,'set',[{dragRestTime:this.c_3}])},value:250},c_q:{name:'fixedX',onChange:c_bn,value:c_c},c_p:{name:'fixedY',onChange:c_bn,value:c_c},c_H:{name:'height',onChange:c_bo,value:200},c_B:{name:'inDrag',value:c_c},c_E:{name:'left',onChange:c_bo,value:0},c_M:{name:'minHeight',value:10,onChange:c_A},c_L:{name:'minWidth',value:10,onChange:c_A},c_F:{name:'top',onChange:c_bo,value:0},c_G:{name:'width',onChange:c_bo,value:200}});return c_g;}});